apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer
      namespace: example
      name: default

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  name: default
  namespace: example
spec:
  addr: ":8080"
  virtualHosts:
    - middleware:
        - apiVersion: app/v1
          kind: AuthenticationMiddleware
          namespace: example
          name: default
      handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler
            namespace: example
            name: default

---
apiVersion: app/v1
kind: EchoHandler
metadata:
  namespace: example
  name: default
spec: {}

---
apiVersion: app/v1
kind: AuthenticationMiddleware
metadata:
  namespace: example
  name: default
spec:
  handlers:
    - apiVersion: app/v1
      kind: OAuthAuthenticationHandler
      namespace: example
      name: default

---
apiVersion: app/v1
kind: OAuthAuthenticationHandler
metadata:
  namespace: example
  name: default
spec:
  contextQueryKey: context
  contextHeaderKey: X-Oauth-Context
  resourceServerHandler: {}
  contexts:
    - name: default
      atProxyHeader: "X-Access-Token"
      enableIntrospection: true
      provider:
        issuer: "http://localhost:18080/realms/aileron"
        baseURL: "http://localhost:18080"
        endpoints:
          discovery: "/realms/aileron/.well-known/openid-configuration"
      client:
        id: "aileron_resource_server"
        secret: "2Ry7fU4a71TEbv3C1vBkMiJvHFUh4jzq"
      jwtHandler:
        publicKeys:
          - keyID: LO9dmmUtUOiV1P7OkzYW-CDbTJV94nADvDFhojxvSqk
            algorithm: RS256
            keyType: PUBLIC
            keyFilePath: ./_devtools/keycloak/keys/public.key
