apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - hosts: []
      middleware:
        - apiVersion: core/v1
          kind: HTTPLogger
      handlers:
        - handler:
            apiVersion: core/v1
            kind: ReverseProxyHandler

---
apiVersion: core/v1
kind: ReverseProxyHandler
spec:
  tripperwares:
    - apiVersion: core/v1
      kind: HTTPLogger
  loadBalancers:
    - pathMatcher:
        match: "/"
        matchType: Prefix
      upstreams:
        - url: http://httpbin.org
        # - url: http://sse.dev/

---
apiVersion: core/v1
kind: HTTPLogger
spec:
  journal: false
  request:
    bodyOutputPath: ""
    mimes:
      - "application/json"
      - "application/xml"
      - "text/plain"
      - "text/html"
      - "text/event-stream"
      - "image/jpeg"
      - "image/png"
      - "application/x-www-form-urlencoded"
    logFormat: "\
      \e[32m%time%\e[0m
      \e[31m%id%\e[0m
      %type%
      %proto%
      %method%
      %host%
      %path%
      %size%
      %header%
      %body%
      "
    headers:
      - name: "*" # Log all headers.
      - name: "Authorization"
        replacers:
          - fixed:
              value: "#MASKED#"
      - name: "Accept"
        replacers:
          # - encrypt:
          #     alg: AESCBC
          #     password: "31323334353637383930313233343536"
          #     encoding: Base16
          - encode:
              encoding: Base64
          - fixed:
              value: "*MASKED*"
    bodies:
      - mime: "application/json"
        replacers:
          - regexp:
              pattern: '"password":"([^"]*)"'
              replace: "*********"
      - mime: "application/x-www-form-urlencoded"
        replacers:
          - regexp:
              pattern: "password=([^&]*)"
              replace: "password=***"
  response:
    bodyOutputPath: ""
    mimes:
      - "application/json"
      - "application/xml"
      - "text/plain"
      - "text/html"
      - "text/event-stream"
      - "image/jpeg"
      - "image/png"
      - "application/x-www-form-urlencoded"
    logFormat: "\
      \e[32m%time%\e[0m
      \e[31m%id%\e[0m
      \e[103m\e[30m%status%\e[0m
      %type%
      %duration%[us]
      %size%[B]
      CT:%header.Content-Type%
      %body%
      "
    headers:
      - name: "*" # Log all headers.
    bodies:
      - mime: "application/json"
        replacers:
          - regexp:
              pattern: '"password":"(.*)"'
              replace: "*********"
