apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer
      name: EchoServer
    - apiVersion: core/v1
      kind: HTTPServer
      name: ReverseProxyServer

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  name: EchoServer
spec:
  addr: ":8000"
  virtualHosts:
    - hosts: []
      handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  name: ReverseProxyServer
spec:
  addr: ":8080"
  virtualHosts:
    - hosts: []
      middleware:
        - apiVersion: app/v1
          kind: SessionMiddleware
      handlers:
        - handler:
            apiVersion: core/v1
            kind: ReverseProxyHandler

---
apiVersion: app/v1
kind: EchoHandler
spec: {}

---
apiVersion: core/v1
kind: ReverseProxyHandler
spec:
  loadBalancers:
    - pathMatcher:
        match: ".*"
        matchType: Regex
      upstreams:
        - url: http://localhost:8000/

---
apiVersion: app/v1
kind: SessionMiddleware
spec:
  # storage:
  #   apiVersion: app/v1
  #   kind: RedisClient
  secureEncoder:
    enableCompression: false
    disableHMAC: true
    disableEncryption: true

---
apiVersion: app/v1
kind: RedisClient
spec:
  expiration: 0
