apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8443"
  http2Config: {}
  http3Config:
    altSvc: h3=":8443";ma=3600,h3-29=":8443";ma=3600
    tlsConfig:
      certKeyPairs:
        - certFile: "./_example/http3-server/pki/cert.crt" # Replace to your cert
          keyFile: "./_example/http3-server/pki/cert.key" # Replace to your key.
  virtualHosts:
    - hosts: []
      handlers:
        - handler:
            apiVersion: core/v1
            kind: ReverseProxyHandler

---
apiVersion: core/v1
kind: ReverseProxyHandler
spec:
  loadBalancers:
    - pathMatcher:
        match: ".*"
        matchType: Regex
      upstreams:
        - url: http://httpbin.org
        # - url: http://worldtimeapi.org
        # - url: http://ipconfig.io
        # - url: http://ifconfig.io
