apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - hosts: []
      middleware:
        - apiVersion: app/v1
          kind: BasicAuthnMiddleware
      handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler

---
apiVersion: app/v1
kind: EchoHandler
spec: {}

---
apiVersion: app/v1
kind: BasicAuthnMiddleware
spec:
  preferError: false
  realm: "example"
  # commonKeyCryptType: AESCBC
  # cryptSecret: ZXhhbXBsZV9wYXNzd29yZA== # Base64("example_password")
  # passwordCrypt:
  #   bcrypt: {}
  #   scrypt:
  #     saltLen: 10
  #     keyLen: 32
  #     n: 16384
  #     r: 8
  #     p: 1
  #   pbkdf2:
  #     saltLen: 10
  #     keyLen: 32
  #     iter: 1024
  #     hashAlg: SHA256
  #   argon2i:
  #     saltLen: 10
  #     keyLen: 32
  #     time: 2
  #     memory: 1024
  #     threads: 4
  #   argon2id:
  #     saltLen: 10
  #     keyLen: 32
  #     time: 2
  #     memory: 1024
  #     threads: 4
  fileProvider:
    # encoding: Base16 # Use when SCrypt, PBKDF2, Argon2i, Argon2id.
    paths:
      - ./_example/authn-basic/users.list
