apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer
      name: echoServer
    - apiVersion: core/v1
      kind: HTTPServer
      name: reverseProxyServer
  finalizers:
    - apiVersion: app/v1
      kind: OpenTelemetryTracer

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  name: echoServer
spec:
  addr: ":8000"
  virtualHosts:
    - handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  name: reverseProxyServer
spec:
  addr: ":8080"
  virtualHosts:
    - hosts: []
      middleware:
        - apiVersion: app/v1
          kind: TrackingMiddleware
        - apiVersion: app/v1
          kind: OpenTelemetryTracer
      handlers:
        - handler:
            apiVersion: core/v1
            kind: ReverseProxyHandler

---
apiVersion: app/v1
kind: EchoHandler

---
apiVersion: core/v1
kind: ReverseProxyHandler
spec:
  loadBalancers:
    - pathMatcher:
        match: ".*"
        matchType: Regex
      upstreams:
        - url: http://localhost:8000/
  roundTripper:
    apiVersion: core/v1
    kind: HTTPClient

---
apiVersion: core/v1
kind: HTTPClient
spec:
  tripperwares:
    - apiVersion: app/v1
      kind: OpenTelemetryTracer

---
apiVersion: app/v1
kind: TrackingMiddleware
spec:
  requestIDProxyName: "X-Request-ID"
  traceIDProxyName: "X-Trace-ID"

---
apiVersion: app/v1
kind: OpenTelemetryTracer
spec:
  grpcExporter:
    insecure: true
    otlpRetry:
      enabled: true
      initialInterval: 5
      maxInterval: 30
      maxElapsedTime: 60
