version: '3'
env:
  AILERON_CMD: "./aileron"
tasks:
  default:
    deps: ["jaeger","run"]
  run:
    cmd: "{{.AILERON_CMD}} -f ./config.yaml"
  jaeger:
    vars:
      PORT: "-p 4317:4317 -p 4318:4318 -p 16686:16686"
      IMAGE: "jaegertracing/jaeger:2.5.0"
    cmd: "docker run --rm  {{.PORT}} {{.IMAGE}}"
