apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer
      namespace: sampleNamespace
      name: MetricsServer
  finalizers:
    - apiVersion: app/v1
      kind: OpenTelemetryMeter
      name: default
      namespace: sampleNamespace

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  name: MetricsServer
  namespace: sampleNamespace
spec:
  addr: ":8080"
  virtualHosts:
    - hosts: []
      middleware:
        - apiVersion: app/v1
          kind: OpenTelemetryMeter
          namespace: sampleNamespace
          name: default
      handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler
            namespace: sampleNamespace
            name: default

---
apiVersion: app/v1
kind: EchoHandler
metadata:
  name: default
  namespace: sampleNamespace
spec:

---
apiVersion: app/v1
kind: OpenTelemetryMeter
metadata:
  name: default
  namespace: sampleNamespace
spec:
  grpcExporter:
    insecure: true
