apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - hosts: []
      handlers:
        - handler:
            apiVersion: core/v1
            kind: TemplateHandler

---
apiVersion: core/v1
kind: TemplateHandler
spec:
  mimeContents:
    - mimeType: text/plain
      statusCode: 500
      templateType: Text
      template: |
        AILERON Gateway
        Hello World!!
    - mimeType: application/json
      statusCode: 500
      templateType: GoText
      template: |
        {
          "app": "AILERON Gateway",
          "hello": "World!"
        }
    - mimeType: text/html
      statusCode: 500
      templateType: GoHTML
      templateFile: _example/template/template.html
