version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dupword
    - durationcheck
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  settings:
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G110
        - G401
        - G404
        - G405
        - G501
        - G502
        - G503
        - G505
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    misspell:
      locale: US
    staticcheck:
      checks: ["all", "-QF1001", "-ST1000", "-ST1003", "-ST1016", "-ST1019", "-ST1020", "-ST1021", "-ST1022"]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: apis/
      - path: (.+)\.go$
        text: test/
    paths:
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - examples$
