# ----------------------------------------
# This is an example docker-compose file.
# This docker-compose is development use only.
# ----------------------------------------

services:
  aileron:
    image: ghcr.io/aileron-gateway/aileron-gateway/aileron
    command: ["-f", "_example/reverse-proxy/"]
    ports:
      - "8080:8080"
    volumes:
      - ./examples:/app/_example:ro
