apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - middleware:
        - apiVersion: app/v1
          kind: SessionMiddleware
        - apiVersion: app/v1
          kind: AuthenticationMiddleware
      handlers:
        - handler:
            apiVersion: core/v1
            kind: ReverseProxyHandler

---
apiVersion: core/v1
kind: ReverseProxyHandler
spec:
  loadBalancers:
    - pathMatcher:
        match: "/"
        matchType: Prefix
      upstreams:
        - url: http://httpbin.org

---
apiVersion: app/v1
kind: SessionMiddleware
spec:
  secureEncoder:
    enableCompression: false
    disableHMAC: true
    disableEncryption: true

---
apiVersion: app/v1
kind: AuthenticationMiddleware
spec:
  handlers:
    - apiVersion: app/v1
      kind: OAuthAuthenticationHandler

---
apiVersion: app/v1
kind: OAuthAuthenticationHandler
spec:
  authorizationCodeHandler:
    redirectPath: "/anything"
    loginPath: "/auth/login"
    callbackURL: "http://localhost:8080/auth/callback"
    redirectToLogin: true
  contexts:
    - name: default
      atProxyHeader: "X-Access-Token"
      idtProxyHeader: "X-ID-Token"
      provider:
        issuer: "http://localhost:18080/realms/aileron"
        baseURL: "http://localhost:18080"
        endpoints:
          discovery: "/realms/aileron/.well-known/openid-configuration"
      tokenRedeemer:
        clientAuthMethod: BasicAuth
      client:
        id: "aileron_authorization_code"
        secret: "KWYPBgrTEEGZNH6wZsP2zyK14LZHJi77"
        scopes:
          - openid
          - profile
      jwtHandler:
        publicKeys:
          - keyID: QJQdUdHaY_OXC8BfO-3tqVV0s64nvrFSffyfqONNeYk
            algorithm: RS256
            keyType: PUBLIC
            keyFilePath: ./keycloak/keys/public.pem
