apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer
      namespace: example
      name: default

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  name: default
  namespace: example
spec:
  addr: ":8080"
  virtualHosts:
    - middleware:
        - apiVersion: app/v1
          kind: SessionMiddleware
          name: default
          namespace: example
        - apiVersion: app/v1
          kind: AuthenticationMiddleware
          namespace: example
          name: default
      handlers:
        - handler:
            apiVersion: core/v1
            kind: ReverseProxyHandler

---
apiVersion: core/v1
kind: ReverseProxyHandler
spec:
  methods:
    - GET
    - POST
    - DELETE
    - PUT
  loadBalancers:
    - pathMatcher:
        match: "/"
        matchType: Prefix
      upstreams:
        - url: http://httpbin.org
          weight: 1

---
apiVersion: app/v1
kind: SessionMiddleware
metadata:
  namespace: example
  name: default
spec:
  secureEncoder:
    enableCompression: false
    disableHMAC: true
    disableEncryption: true

---
apiVersion: app/v1
kind: AuthenticationMiddleware
metadata:
  namespace: example
  name: default
spec:
  handlers:
    - apiVersion: app/v1
      kind: OAuthAuthenticationHandler
      namespace: example
      name: default

---
apiVersion: app/v1
kind: OAuthAuthenticationHandler
metadata:
  namespace: example
  name: default
spec:
  contextQueryKey: context
  contextHeaderKey: X-Oauth-Context
  authorizationCodeHandler:
    disableState: false
    disableNonce: false
    disablePKCE: false
    redirectPath: "/anything"
    redirectPathPattern: /*
    loginPath: "/auth/login"
    callbackURL: "http://localhost:8080/auth/callback"
    redirectToLogin: false
    unauthorizeAny: false
    restoreRequest: false
    # urlParams:
    #   - "max_age=120"
    #   - "login_hint=test"
    UserInfoPath: /auth/userinfo
  contexts:
    - name: default
      atProxyHeader: "X-Access-Token"
      idtProxyHeader: "X-ID-Token"
      enableIntrospection: false
      provider:
        issuer: "http://localhost:18080/realms/aileron"
        baseURL: "http://localhost:18080"
        endpoints:
          discovery: "/realms/aileron/.well-known/openid-configuration"
      tokenRedeemer:
        clientAuthMethod: BasicAuth
      client:
        id: "aileron_authorization_code"
        secret: "NNJxpasHJgwGmgTYMoVFTKGUWZxp12bl"
        scopes:
          - openid
          - profile
          - read
      jwtHandler:
        publicKeys:
          - keyID: LO9dmmUtUOiV1P7OkzYW-CDbTJV94nADvDFhojxvSqk
            algorithm: RS256
            keyType: PUBLIC
            keyFilePath: ./_devtools/keycloak/keys/public.key
