version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: aileron-keycloak
    ports:
      - "18080:8080"
      - "18443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command:
      - "start-dev"
      - "--import-realm"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak/keys:/opt/keycloak/data/keys
      - ./keycloak/conf:/opt/keycloak/conf
