apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - middleware:
        - apiVersion: app/v1
          kind: ThrottleMiddleware
      handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler

---
apiVersion: app/v1
kind: EchoHandler

---
apiVersion: app/v1
kind: ThrottleMiddleware
spec:
  apiThrottlers:
    - matcher:
        matchType: Regex
        patterns:
          - ".*"
      # fixedWindow:
      #   windowSize: 1000
      #   limit: 10
      # maxConnections:
      #   maxConns: 5
      tokenBucket:
        bucketSize: 20
        fillRate: 10
      # leakyBucket:
      #   bucketSize: 10
      #   leakInterval: 100

