apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - hosts: []
      middleware:
        - apiVersion: app/v1
          kind: ThrottleMiddleware
      handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler

---
apiVersion: app/v1
kind: EchoHandler

---
apiVersion: app/v1
kind: ThrottleMiddleware
spec:
  apiThrottlers:
    - methods:
        - GET
      matcher:
        matchType: Regex
        patterns:
          - ".*"
      maxRetry: 3
      # waiter:
      #   exponentialBackoffFullJitter:
      #     base: 2
      #     # max: 2147483647

      # fixedWindow:
      #   windowSize: 100
      #   limit: 10

      # maxConnections:
      #   maxConns: 10

      tokenBucket:
        bucketSize: 10
        fillRate: 5

      # leakyBucket:
      #   bucketSize: 10
      #   leakRate: 5
