apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - hosts: []
      middleware:
        - apiVersion: app/v1
          kind: BasicAuthnMiddleware
        - apiVersion: app/v1
          kind: CasbinAuthzMiddleware
      handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler

---
apiVersion: app/v1
kind: EchoHandler
spec: {}

---
apiVersion: app/v1
kind: CasbinAuthzMiddleware
spec:
  enforcers:
    - modelPath: ./_example/casbin/model/abac_map_model.conf
      policyPath: ./_example/casbin/model/abac_map_policy.csv
  explain: true

---
apiVersion: app/v1
kind: BasicAuthnMiddleware
spec:
  passwordCrypt:
    bcrypt: {}
  fileProvider:
    paths:
      - ./_example/casbin/htpasswd
