apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - middleware:
        # - apiVersion: app/v1
        #   kind: SessionMiddleware
        - apiVersion: app/v1
          kind: AuthenticationMiddleware
      handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler

---
apiVersion: app/v1
kind: EchoHandler
spec: {}

---
apiVersion: app/v1
kind: SessionMiddleware
spec:
  secureEncoder:
    enableCompression: false
    disableHMAC: true
    disableEncryption: true

---
apiVersion: app/v1
kind: AuthenticationMiddleware
spec:
  handlers:
    - apiVersion: app/v1
      kind: OAuthAuthenticationHandler

---
apiVersion: app/v1
kind: OAuthAuthenticationHandler
spec:
  contextQueryKey: context
  contextHeaderKey: X-Oauth-Context
  clientCredentialsHandler: {}
  contexts:
    - name: default
      atProxyHeader: "X-Access-Token"
      idtProxyHeader: "X-ID-Token"
      enableIntrospection: false
      provider:
        issuer: "http://localhost:18080/realms/aileron"
        baseURL: "http://localhost:18080"
        endpoints:
          discovery: "/realms/aileron/.well-known/openid-configuration"
      client:
        id: "aileron_client_credentials"
        secret: "j9wEw6Zj3dhGIhVzGCD1jpsDLDkMl8wD"
        audience: "account"
        scopes:
          - openid
          - profile
      jwtHandler:
        publicKeys:
          - keyID: LO9dmmUtUOiV1P7OkzYW-CDbTJV94nADvDFhojxvSqk
            algorithm: RS256
            keyType: PUBLIC
            keyFilePath: ./_devtools/keycloak/keys/public.key
