version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.74.0
    volumes:
      - ./config.yaml:/etc/config.yaml
    command:
      --config=/etc/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
    environment:
      - no_proxy=localhost,127.0.0.1,otel-collector,prometheus
    networks:
      - otel-collector
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus:v2.42.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    environment:
      - no_proxy=localhost,127.0.0.1,otel-collector,prometheus
    networks:
      - otel-collector
      - prometheus
      - grafana

  grafana:
    image: grafana/grafana:9.4.3
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - no_proxy=localhost,127.0.0.1,otel-collector,prometheus
    networks:
      - otel-collector
      - prometheus
      - grafana

networks:
  otel-collector:
  prometheus:
  grafana: