apiVersion: core/v1
kind: Entrypoint
spec:
  defaultLogger:
    apiVersion: core/v1
    kind: SLogger
  defaultErrorHandler:
    apiVersion: core/v1
    kind: ErrorHandler
  runners:
    - apiVersion: core/v1
      kind: HTTPServer
      name: reverseProxyServer

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  name: reverseProxyServer
spec:
  addr: "localhost:8000"
  virtualHosts:
    - hosts: []
      middleware:
        - apiVersion: app/v1
          kind: SOAPRESTMiddleware
      handlers:
        - handler:
            apiVersion: core/v1
            kind: ReverseProxyHandler

---
apiVersion: core/v1
kind: ReverseProxyHandler
spec:
  loadBalancers:
    - pathMatcher:
        match: ".*"
        matchType: Regex
      upstreams:
        - url: http://localhost:8080/

---
apiVersion: core/v1
kind: SLogger
spec:
  level: Debug

---
apiVersion: core/v1
kind: ErrorHandler
spec:
  errorMessages:
    - codes: ["E3216"]
      mimeContents:
        - mimeType: text/xml
          statusCode: 403
          templateFile: ./_example/soap-rest/error-messages/soapfault_versionmismatch.txt

    - codes: ["E3217", "E3218"]
      mimeContents:
        - mimeType: text/xml
          statusCode: 400
          templateFile: ./_example/soap-rest/error-messages/soapfault_client.txt

    - codes: ["E3219", "E3220"]
      mimeContents:
        - mimeType: text/xml
          statusCode: 500
          templateFile: ./_example/soap-rest/error-messages/soapfault_server.txt

---
apiVersion: app/v1
kind: SOAPRESTMiddleware
spec:
  matcher:
    patterns: ["/"]
    matchType: Contains