apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer
      name: hello-server
    - apiVersion: core/v1
      kind: HTTPServer
      name: goodbye-server

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  name: hello-server
spec:
  addr: ":8081"
  virtualHosts:
    - handlers:
        - handler:
            apiVersion: core/v1
            kind: TemplateHandler
            name: hello

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  name: goodbye-server
spec:
  addr: ":8082"
  virtualHosts:
    - handlers:
        - handler:
            apiVersion: core/v1
            kind: TemplateHandler
            name: goodbye

---
apiVersion: core/v1
kind: TemplateHandler
metadata:
  name: hello
spec:
  mimeContents:
    - mimeType: text/plain
      statusCode: 200
      templateType: Text
      template: "Hello!!"

---
apiVersion: core/v1
kind: TemplateHandler
metadata:
  name: goodbye
spec:
  mimeContents:
    - mimeType: text/plain
      statusCode: 200
      templateType: Text
      template: "Goodbye!!"
