version: "3"

services:

  jaeger:
    image: jaegertracing/all-in-one:1.63.0
    ports:
    # Checkout the ports at
    # https://www.jaegertracing.io/docs/1.43/apis/
    # https://www.jaegertracing.io/docs/next-release/deployment/
    # https://www.jaegertracing.io/docs/1.43/monitoring/
      - "5775:5775/udp" # UDP agent accept zipkin.thrift over compact thrift protocol
      - "6831:6831/udp" # UDP agent accept jaeger.thrift over compact thrift protocol
      - "6832:6832/udp" # UDP agent accept jaeger.thrift over binary thrift protocol
      - "4317:4317"     # gRPC Accepts traces in OpenTelemetry OTLP format
      - "4318:4318"     # HTTP Accepts traces in OpenTelemetry OTLP format
      - "5778:5778"     # HTTP agent serve configs
      - "16685:16685"   # gRPC Protobuf/gRPC QueryService
      - "16686:16686"   # HTTP query serve frontend
      - "16687:16687"   # admin port: health check at / and metrics at /metrics
      - "14268:14268"   # HTTP collector accept jaeger.thrift directly from clients
      - "9411:9411"     # HTTP collector Zipkin compatible endpoint
      - "14270:14270"   # HTTP admin port: health check at / and metrics at /metrics
      - "14269:14269"   # all-in-one prometheus metrics port
    environment:
      # Check other environment variable from the link below.
      # https://www.jaegertracing.io/docs/1.42/deployment/
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - SPAN_STORAGE_TYPE=memory
      - LOG_LEVEL=debug
