apiVersion: core/v1
kind: Entrypoint
spec:
  defaultErrorHandler:
    apiVersion: core/v1
    kind: ErrorHandler
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - middleware:
        - apiVersion: app/v1
          kind: HeaderPolicyMiddleware
      handlers:
        - handler:
            apiVersion: core/v1
            kind: StaticFileHandler

---
apiVersion: app/v1
kind: HeaderPolicyMiddleware
spec:
  allowMIMEs: # HTML is not allowed (to generate an error).
    - "application/json"

---
apiVersion: core/v1
kind: StaticFileHandler
spec:
  rootDir: "./html/"
  enableListing: true

---
apiVersion: core/v1
kind: ErrorHandler
spec:
  stackAlways: false
  errorMessages:
    - paths: ["^/foo*", "^/bar.*"]
      codes: ["*"]
      mimeContents:
        - mimeType: text/plain
          statusCode: 500
          templateType: GoText
          template: |
              msg: "^/foo*" or "^/bar.*"
              code: {{.code}}
              kind: {{.kind}}
    - paths: ["^/baz.*"]
      codes: ["*"]
      mimeContents:
        - mimeType: text/plain
          statusCode: 500
          templateType: GoText
          template: |
              msg: "^/baz.*"
              "code": "{{.code}}"
              "kind": "{{.kind}}"
    - paths: [] # Match all paths.
      codes: ["*"] # OR condition
      kinds: []    # OR condition
      messages: [] # OR condition
      headerTemplate:
        "X-Example": "status={{status}}"
      mimeContents:
        - mimeType: application/json
          statusCode: 500
          templateType: GoText
          template: |
            {
              "app": "AILERON Gateway",
              "status": {{.status}},
              "statusText": "{{.statusText}}",
              "code": "{{.code}}",
              "kind": "{{.kind}}"
            }
        - mimeType: application/xml
          statusCode: 0
          templateType: GoText
          template: |
            <?xml version="1.0" encoding="UTF-8" ?>
            <error>
                <app>AILERON Gateway</app>
                <status>{{.status}}</status>
                <statusText>{{.statusText}}</statusText>
                <code>{{.code}}</code>
                <kind>{{.kind}}</kind>
            </error>
