apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - hosts: []
      middleware:
        - apiVersion: app/v1
          kind: BodyLimitMiddleware
      handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler

---
apiVersion: app/v1
kind: EchoHandler
spec: {}

---
apiVersion: app/v1
kind: BodyLimitMiddleware
spec:
  maxSize: 20
  memLimit: 5
  tempPath: "./"
# ---
# apiVersion: core/v1
# kind: ReverseProxyHandler
# spec:
#   # patterns:
#   #   - "/"
#   # methods:
#   loadBalancers:
#     - pathMatcher:
#         match: ".*"
#         matchType: Regex
#       upstreams:
#         # - url: http://postman-echo.com
#         # - url: http://worldtimeapi.org
#         - url: http://httpbin.org
#         # - url: http://localhost:8000/
