version: "3"

services:

  prometheus:
    image: prom/prometheus:v2.42.0
    hostname: prometheus
    restart: always
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    environment: []
    volumes:
      - ./:/etc/prometheus/
    networks:
      - prometheus
      - nodeexporter
      - alertmanager
      - grafana

  node-exporter:
    image: prom/node-exporter:v1.5.0
    hostname: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - prometheus
      - nodeexporter
      - alertmanager
      - grafana

  alertmanager:
    image: prom/alertmanager:v0.25.0
    hostname: alertmanager
    restart: always
    ports:
      - 9093:9093
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yaml"
      - "--storage.path=/alertmanager"
    volumes:
      - ./:/etc/alertmanager/
    networks:
      - prometheus
      - nodeexporter
      - alertmanager
      - grafana

  grafana:
    image: grafana/grafana:9.4.3
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - prometheus
      - nodeexporter
      - alertmanager
      - grafana

networks:
  prometheus:
  nodeexporter:
  alertmanager:
  grafana: