apiVersion: core/v1
kind: Entrypoint
spec:
  defaultErrorHandler:
    apiVersion: core/v1
    kind: ErrorHandler
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: "localhost:8080"
  virtualHosts:
    - middleware:
        - apiVersion: app/v1
          kind: SOAPRESTMiddleware
      handlers:
        - handler:
            apiVersion: core/v1
            kind: ReverseProxyHandler

---
apiVersion: core/v1
kind: ReverseProxyHandler
spec:
  loadBalancers:
    - pathMatcher:
        match: ".*"
        matchType: Regex
      upstreams:
        - url: http://localhost:9090/

---
apiVersion: app/v1
kind: SOAPRESTMiddleware
spec:
  simple:
    trimSpace: true

---
apiVersion: core/v1
kind: ErrorHandler
spec:
  errorMessages:
    - codes: ["E3216"]
      mimeContents:
        - mimeType: text/xml
          statusCode: 403
          templateFile: ./errors/version.xml
    - codes: ["E3217", "E3218"]
      mimeContents:
        - mimeType: text/xml
          statusCode: 400
          templateFile: ./_example/soap-rest/error-messages/soapfault_client.txt

    - codes: ["E3219", "E3220", "E3221"]
      mimeContents:
        - mimeType: text/xml
          statusCode: 500
          templateFile: ./_example/soap-rest/error-messages/soapfault_server.txt

---
apiVersion: app/v1
kind: SOAPRESTMiddleware
spec: