version: '3'
env:
  AILERON_CMD: "./aileron"
tasks:
  default:
    deps: ["echo", "config"]
  config:
    cmd: "{{.AILERON_CMD}} -f ./config.yaml"
  echo:
    cmd: "go run ./echo.go"

  config-error:
    cmd: "{{.AILERON_CMD}} -f ./config-error.yaml"
