apiVersion: core/v1
kind: Entrypoint
spec:
  defaultLogger:
    apiVersion: core/v1
    kind: SLogger
    namespace: example
    name: default
  runners:
    - apiVersion: core/v1
      kind: HTTPServer
      namespace: example
      name: echoServer

---
apiVersion: core/v1
kind: SLogger
metadata:
  name: default
  namespace: example
spec:
  level: "Debug"

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  namespace: example
  name: echoServer
spec:
  addr: ":8080"
  virtualHosts:
    - hosts: []
      middleware:
        - apiVersion: app/v1
          kind: CompressionMiddleware
          namespace: example
          name: default
      handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler
            namespace: example
            name: default

---
apiVersion: app/v1
kind: EchoHandler
metadata:
  namespace: example
  name: default
spec: {}

---
apiVersion: app/v1
kind: CompressionMiddleware
metadata:
  namespace: example
  name: default
spec:
  minimumSize: 1024
