version: "3"
services:
  postgres:
    image: postgres:17.5-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak
    ports:
      - "18080:8080"
      - "18443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    command:
      - "start-dev"
      - "--import-realm"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak/keys:/opt/keycloak/data/keys
      - ./keycloak/conf:/opt/keycloak/conf
