// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: app/v1/middleware/protocolconversion/soaptorest.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	kernel "github.com/aileron-gateway/aileron-gateway/apis/kernel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SoapToRestMiddleware is the definition of the SoapToRestMiddleware object.
// SoapToRestMiddleware implements interface of the middleware.
type SoapToRestMiddleware struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// [REQUIRED]
	// APIVersion is the defined version of the middleware.
	// This value must be "app/v1".
	APIVersion string `protobuf:"bytes,1,opt,name=APIVersion,json=apiVersion,proto3" json:"APIVersion,omitempty"`
	// [REQUIRED]
	// Kind is the kind of this object.
	// This value must be "SoapToRestMiddleware".
	Kind string `protobuf:"bytes,2,opt,name=Kind,json=kind,proto3" json:"Kind,omitempty"`
	// [OPTIONAL]
	// Metadata is the metadata of the http logger object.
	// If not set, both name and namespace in the metadata
	// are treated as "default".
	Metadata *kernel.Metadata `protobuf:"bytes,3,opt,name=Metadata,json=metadata,proto3" json:"Metadata,omitempty"`
	// [OPTIONAL]
	// Spec is the specification of the middleware.
	// Default values are used when nothing is set.
	Spec *SoapToRestMiddlewareSpec `protobuf:"bytes,4,opt,name=Spec,json=spec,proto3" json:"Spec,omitempty"`
}

func (x *SoapToRestMiddleware) Reset() {
	*x = SoapToRestMiddleware{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_v1_middleware_protocolconversion_soaptorest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoapToRestMiddleware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoapToRestMiddleware) ProtoMessage() {}

func (x *SoapToRestMiddleware) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_middleware_protocolconversion_soaptorest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoapToRestMiddleware.ProtoReflect.Descriptor instead.
func (*SoapToRestMiddleware) Descriptor() ([]byte, []int) {
	return file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDescGZIP(), []int{0}
}

func (x *SoapToRestMiddleware) GetAPIVersion() string {
	if x != nil {
		return x.APIVersion
	}
	return ""
}

func (x *SoapToRestMiddleware) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SoapToRestMiddleware) GetMetadata() *kernel.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SoapToRestMiddleware) GetSpec() *SoapToRestMiddlewareSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// SoapToRestMiddlewareSpec is the status of the SoapToRestMiddleware object.
// Values are managed by the application and therefore should not be set by users.
type SoapToRestMiddlewareSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// [OPTIONAL]
	// ErrorHandler is the reference to a ErrorHandler object.
	// Referred object must implement ErrorHandler interface.
	// Default error handler is used when not set.
	ErrorHandler *kernel.Reference `protobuf:"bytes,1,opt,name=ErrorHandler,json=errorHandler,proto3" json:"ErrorHandler,omitempty"`
	// [OPTIONAL]
	// <TODO> implement validation like (buf.validate.field).string.pattern = "^[0-9a-zA-Z-_:]*$"
	AttributeKey string `protobuf:"bytes,2,opt,name=AttributeKey,json=attributeKey,proto3" json:"AttributeKey,omitempty"`
	// [OPTIONAL]
	// <TODO> implement validation like (buf.validate.field).string.pattern = "^[0-9a-zA-Z-_:]*$"
	TextKey string `protobuf:"bytes,3,opt,name=TextKey,json=textKey,proto3" json:"TextKey,omitempty"`
	// [OPTIONAL]
	// <TODO> implement validation like (buf.validate.field).string.pattern = "^[0-9a-zA-Z-_:]*$"
	NameSpaceKey string `protobuf:"bytes,4,opt,name=NameSpaceKey,json=nameSpaceKey,proto3" json:"NameSpaceKey,omitempty"`
	// [OPTIONAL]
	// <TODO> implement validation like (buf.validate.field).string.pattern = "^[0-9a-zA-Z-_:]*$"
	// <TODO> consider whether we need this configuration.
	ArrayKey string `protobuf:"bytes,5,opt,name=ArrayKey,json=arrayKey,proto3" json:"ArrayKey,omitempty"`
	// [OPTIONAL]
	// <TODO> consider whether we need this configuration.
	SeparatorChar string `protobuf:"bytes,6,opt,name=SeparatorChar,json=separatorChar,proto3" json:"SeparatorChar,omitempty"`
}

func (x *SoapToRestMiddlewareSpec) Reset() {
	*x = SoapToRestMiddlewareSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_v1_middleware_protocolconversion_soaptorest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoapToRestMiddlewareSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoapToRestMiddlewareSpec) ProtoMessage() {}

func (x *SoapToRestMiddlewareSpec) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_middleware_protocolconversion_soaptorest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoapToRestMiddlewareSpec.ProtoReflect.Descriptor instead.
func (*SoapToRestMiddlewareSpec) Descriptor() ([]byte, []int) {
	return file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDescGZIP(), []int{1}
}

func (x *SoapToRestMiddlewareSpec) GetErrorHandler() *kernel.Reference {
	if x != nil {
		return x.ErrorHandler
	}
	return nil
}

func (x *SoapToRestMiddlewareSpec) GetAttributeKey() string {
	if x != nil {
		return x.AttributeKey
	}
	return ""
}

func (x *SoapToRestMiddlewareSpec) GetTextKey() string {
	if x != nil {
		return x.TextKey
	}
	return ""
}

func (x *SoapToRestMiddlewareSpec) GetNameSpaceKey() string {
	if x != nil {
		return x.NameSpaceKey
	}
	return ""
}

func (x *SoapToRestMiddlewareSpec) GetArrayKey() string {
	if x != nil {
		return x.ArrayKey
	}
	return ""
}

func (x *SoapToRestMiddlewareSpec) GetSeparatorChar() string {
	if x != nil {
		return x.SeparatorChar
	}
	return ""
}

var File_app_v1_middleware_protocolconversion_soaptorest_proto protoreflect.FileDescriptor

var file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDesc = []byte{
	0x0a, 0x35, 0x61, 0x70, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77,
	0x61, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x6f, 0x61, 0x70, 0x74, 0x6f, 0x72, 0x65, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x1a,
	0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x6b, 0x65,
	0x72, 0x6e, 0x65, 0x6c, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xda, 0x01, 0x0a, 0x14, 0x53, 0x6f, 0x61, 0x70, 0x54, 0x6f, 0x52, 0x65,
	0x73, 0x74, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x12, 0x2d, 0x0a, 0x0a,
	0x41, 0x50, 0x49, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x0d, 0xba, 0x48, 0x0a, 0x72, 0x08, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x2f, 0x76, 0x31, 0x52,
	0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x04, 0x4b,
	0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1b, 0xba, 0x48, 0x18, 0x72, 0x16,
	0x0a, 0x14, 0x53, 0x6f, 0x61, 0x70, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x74, 0x4d, 0x69, 0x64, 0x64,
	0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x2c, 0x0a, 0x08,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x04, 0x53, 0x70,
	0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x6f, 0x61, 0x70, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x74, 0x4d, 0x69, 0x64, 0x64,
	0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63,
	0x22, 0xf5, 0x01, 0x0a, 0x18, 0x53, 0x6f, 0x61, 0x70, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x74, 0x4d,
	0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x35, 0x0a,
	0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x65, 0x78, 0x74,
	0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x78, 0x74, 0x4b,
	0x65, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x61, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x72, 0x72, 0x61, 0x79, 0x4b,
	0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x72, 0x61, 0x79, 0x4b,
	0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x43,
	0x68, 0x61, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x70, 0x61, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x72, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x6f, 0x6e, 0x2d, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x6f, 0x6e, 0x2d, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDescOnce sync.Once
	file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDescData = file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDesc
)

func file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDescGZIP() []byte {
	file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDescOnce.Do(func() {
		file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDescData)
	})
	return file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDescData
}

var file_app_v1_middleware_protocolconversion_soaptorest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_v1_middleware_protocolconversion_soaptorest_proto_goTypes = []interface{}{
	(*SoapToRestMiddleware)(nil),     // 0: app.v1.SoapToRestMiddleware
	(*SoapToRestMiddlewareSpec)(nil), // 1: app.v1.SoapToRestMiddlewareSpec
	(*kernel.Metadata)(nil),          // 2: kernel.Metadata
	(*kernel.Reference)(nil),         // 3: kernel.Reference
}
var file_app_v1_middleware_protocolconversion_soaptorest_proto_depIdxs = []int32{
	2, // 0: app.v1.SoapToRestMiddleware.Metadata:type_name -> kernel.Metadata
	1, // 1: app.v1.SoapToRestMiddleware.Spec:type_name -> app.v1.SoapToRestMiddlewareSpec
	3, // 2: app.v1.SoapToRestMiddlewareSpec.ErrorHandler:type_name -> kernel.Reference
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_v1_middleware_protocolconversion_soaptorest_proto_init() }
func file_app_v1_middleware_protocolconversion_soaptorest_proto_init() {
	if File_app_v1_middleware_protocolconversion_soaptorest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_v1_middleware_protocolconversion_soaptorest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoapToRestMiddleware); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_v1_middleware_protocolconversion_soaptorest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoapToRestMiddlewareSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_v1_middleware_protocolconversion_soaptorest_proto_goTypes,
		DependencyIndexes: file_app_v1_middleware_protocolconversion_soaptorest_proto_depIdxs,
		MessageInfos:      file_app_v1_middleware_protocolconversion_soaptorest_proto_msgTypes,
	}.Build()
	File_app_v1_middleware_protocolconversion_soaptorest_proto = out.File
	file_app_v1_middleware_protocolconversion_soaptorest_proto_rawDesc = nil
	file_app_v1_middleware_protocolconversion_soaptorest_proto_goTypes = nil
	file_app_v1_middleware_protocolconversion_soaptorest_proto_depIdxs = nil
}
