apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - handlers:
        - middleware:
            - apiVersion: app/v1
              kind: CSRFMiddleware
          handler:
            apiVersion: app/v1
            kind: EchoHandler
        - handler:
            apiVersion: app/v1
            kind: CSRFMiddleware

---
apiVersion: app/v1
kind: EchoHandler

---
apiVersion: app/v1
kind: CSRFMiddleware
spec:
  customRequestHeader:
    headerName: __csrfToken
    allowedPattern: ""
  # doubleSubmitCookies:
  #   cookieName: __csrfToken
  #   tokenSource: Header
  #   sourceKey: __csrfToken
  # synchronizerToken:
  #   tokenSource: Header
  #   sourceKey: __csrfToken
