// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: core/v1/httpproxy.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	kernel "github.com/aileron-gateway/aileron-gateway/apis/kernel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReverseProxyHandler is the definition of the ReverseProxyHandler object.
// ReverseProxyHandler implements interface of the http handler.
type ReverseProxyHandler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [REQUIRED]
	// APIVersion is the defined version of the handler.
	// This value must be "core/v1".
	APIVersion string `protobuf:"bytes,1,opt,name=APIVersion,json=apiVersion,proto3" json:"APIVersion,omitempty"`
	// [REQUIRED]
	// Kind is the kind of this object.
	// This value must be "ReverseProxyHandler".
	Kind string `protobuf:"bytes,2,opt,name=Kind,json=kind,proto3" json:"Kind,omitempty"`
	// [OPTIONAL]
	// Metadata is the metadata of the proxy object.
	// If not set, both name and namespace in the metadata
	// are treated as "default".
	Metadata *kernel.Metadata `protobuf:"bytes,3,opt,name=Metadata,json=metadata,proto3" json:"Metadata,omitempty"`
	// [OPTIONAL]
	// Spec is the specification of the handler.
	// Default values are used when nothing is set.
	Spec          *ReverseProxyHandlerSpec `protobuf:"bytes,4,opt,name=Spec,json=spec,proto3" json:"Spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseProxyHandler) Reset() {
	*x = ReverseProxyHandler{}
	mi := &file_core_v1_httpproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseProxyHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseProxyHandler) ProtoMessage() {}

func (x *ReverseProxyHandler) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_httpproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseProxyHandler.ProtoReflect.Descriptor instead.
func (*ReverseProxyHandler) Descriptor() ([]byte, []int) {
	return file_core_v1_httpproxy_proto_rawDescGZIP(), []int{0}
}

func (x *ReverseProxyHandler) GetAPIVersion() string {
	if x != nil {
		return x.APIVersion
	}
	return ""
}

func (x *ReverseProxyHandler) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ReverseProxyHandler) GetMetadata() *kernel.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ReverseProxyHandler) GetSpec() *ReverseProxyHandlerSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// ReverseProxyHandlerSpec is the specifications for the ReverseProxyHandler object.
type ReverseProxyHandlerSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [OPTIONAL]
	// ErrorHandler is the reference to a ErrorHandler object.
	// Referred object must implement ErrorHandler interface.
	// Default error handler is used when not set.
	ErrorHandler *kernel.Reference `protobuf:"bytes,1,opt,name=ErrorHandler,json=errorHandler,proto3" json:"ErrorHandler,omitempty"`
	// [OPTIONAL]
	// Patterns is path patterns that this handler is registered to a server.
	// Default is not set.
	Patterns []string `protobuf:"bytes,2,rep,name=Patterns,json=patterns,proto3" json:"Patterns,omitempty"`
	// [OPTIONA]
	// Methods is the list of HTTP method this handler can handle.
	// Note that it depends on the multiplexer, or HTTP router
	// if this field can be used.
	// If not set, all methods are accepted.
	// Default is not set.
	Methods []HTTPMethod `protobuf:"varint,3,rep,packed,name=Methods,json=methods,proto3,enum=core.v1.HTTPMethod" json:"Methods,omitempty"`
	// [OPTIONAL]
	// Tripperwares is the list of references to Tripperwares  object.
	// Referred object must implement Tripperware interface.
	// Default is not set.
	Tripperwares []*kernel.Reference `protobuf:"bytes,4,rep,name=Tripperwares,json=tripperwares,proto3" json:"Tripperwares,omitempty"`
	// [OPTIONAL]
	// RoundTripper is the references to a roundTripper  object.
	// Referred object must implement RoundTripper interface.
	// Default roundTripper is used when not set.
	RoundTripper *kernel.Reference `protobuf:"bytes,5,opt,name=RoundTripper,json=roundTripper,proto3" json:"RoundTripper,omitempty"`
	// [OPTIONAL]
	// LoadBalancers is the list of load balancers.
	// Proxy upstreams are specified in this field.
	// Requests will be proxied to the first matched upstream
	// by matching with the load balancers defined order.
	// Default is not set.
	LoadBalancers []*LoadBalancerSpec `protobuf:"bytes,6,rep,name=LoadBalancers,json=loadBalancers,proto3" json:"LoadBalancers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseProxyHandlerSpec) Reset() {
	*x = ReverseProxyHandlerSpec{}
	mi := &file_core_v1_httpproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseProxyHandlerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseProxyHandlerSpec) ProtoMessage() {}

func (x *ReverseProxyHandlerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_httpproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseProxyHandlerSpec.ProtoReflect.Descriptor instead.
func (*ReverseProxyHandlerSpec) Descriptor() ([]byte, []int) {
	return file_core_v1_httpproxy_proto_rawDescGZIP(), []int{1}
}

func (x *ReverseProxyHandlerSpec) GetErrorHandler() *kernel.Reference {
	if x != nil {
		return x.ErrorHandler
	}
	return nil
}

func (x *ReverseProxyHandlerSpec) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *ReverseProxyHandlerSpec) GetMethods() []HTTPMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *ReverseProxyHandlerSpec) GetTripperwares() []*kernel.Reference {
	if x != nil {
		return x.Tripperwares
	}
	return nil
}

func (x *ReverseProxyHandlerSpec) GetRoundTripper() *kernel.Reference {
	if x != nil {
		return x.RoundTripper
	}
	return nil
}

func (x *ReverseProxyHandlerSpec) GetLoadBalancers() []*LoadBalancerSpec {
	if x != nil {
		return x.LoadBalancers
	}
	return nil
}

// LoadBalancerSpec is the specification of LoadBalancer objects.
type LoadBalancerSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [OPTIONAL]
	// LBAlgorithm specifies the load balancing algorithm.
	// Default RoundRobin will be used if not set.
	// Default is not set.
	LBAlgorithm LBAlgorithm `protobuf:"varint,1,opt,name=LBAlgorithm,json=lbAlgorithm,proto3,enum=core.v1.LBAlgorithm" json:"LBAlgorithm,omitempty"`
	// [REQUIRED]
	// Upstreams is the list of upstream server of proxy target.
	// An internal server error will be returned when no upstreams are defined.
	// Default is not set.
	Upstreams []*UpstreamSpec `protobuf:"bytes,2,rep,name=Upstreams,json=upstreams,proto3" json:"Upstreams,omitempty"`
	// [OPTIONAL]
	// PathMatcher is the path matching algorithm to be used.
	// If need multiple path matchers, use PathMatchers field instead.
	// If both PathMatcher and PathMatchers are set, the PathMatcher
	// is appended as the first matcher of PathMatchers.
	// If both PathMatcher and PathMatchers are not set,
	// HTTP error responses are returned to all requests.
	// Default is not set.
	PathMatcher *PathMatcherSpec `protobuf:"bytes,3,opt,name=PathMatcher,json=pathMatcher,proto3" json:"PathMatcher,omitempty"`
	// [OPTIONAL]
	// PathMatchers is the list of path matching algorithm to be used.
	// A prefix matcher with "/" prefix will be used which matches all
	// requests if not set.
	// If need only 1 path matcher, PathMatcher field can be used instead.
	// If both PathMatcher and PathMatchers are set, the PathMatcher
	// is appended as the first matcher of PathMatchers.
	// HTTP error responses are returned to all requests.
	// Matchers are OR condition and the first matched one is used.
	// Default is not set.
	PathMatchers []*PathMatcherSpec `protobuf:"bytes,4,rep,name=PathMatchers,json=pathMatchers,proto3" json:"PathMatchers,omitempty"`
	// [OPTIONAL]
	// Methods is the list of HTTP method this loadbalancer can accept.
	// If not set, all methods are accepted.
	// Default is not set.
	Methods []HTTPMethod `protobuf:"varint,5,rep,packed,name=Methods,json=methods,proto3,enum=core.v1.HTTPMethod" json:"Methods,omitempty"`
	// [OPTIONAL]
	// Hosts is the list of hosts to allow.
	// If not set, all hosts are allowed.
	// List all host names because the value are matched by exact matching algorithm.
	// Wildcard characters such as "*" are not available.
	// Default is not set.
	Hosts []string `protobuf:"bytes,6,rep,name=Hosts,json=hosts,proto3" json:"Hosts,omitempty"`
	// [OPTIONAL]
	// PathParamMatcher is the path parameter value matcher to check
	// if this loadbalancer can accept the target request.
	// Path parameter is only available when the handler was registered
	// to a server with patterns containing path parameters
	// described at https://pkg.go.dev/net/http#hdr-Patterns.
	// Listed matchers are evaluated by AND condition.
	// If OR matching condition is necessary, set the condition within a single matcher.
	// Default is not set.
	PathParamMatchers []*ParamMatcherSpec `protobuf:"bytes,7,rep,name=PathParamMatchers,json=pathParamMatchers,proto3" json:"PathParamMatchers,omitempty"`
	// [OPTIONAL]
	// HeaderMatcher is the header value matcher to check
	// if this loadbalancer can accept the target request.
	// If multiple header values were found, they are joined
	// with a comma "," and agggregated to a singled string.
	// For example ["foo", "bar"] will be "foo,bar" and the matcher
	// is applied to the joined value "foo,bar".
	// Listed matchers are evaluated by AND condition.
	// If OR matching condition is necessary, set the condition within a single matcher.
	// Default is not set.
	HeaderMatchers []*ParamMatcherSpec `protobuf:"bytes,8,rep,name=HeaderMatchers,json=headerMatchers,proto3" json:"HeaderMatchers,omitempty"`
	// [OPTIONAL]
	// QueryMatcher is the URL query value matcher to check
	// this loadbalancer can accept the target request.
	// If multiple query values were found, they are joined
	// with a comma "," and agggregated to a singled string.
	// For example ["foo", "bar"] will be "foo,bar" and the matcher
	// is applied to the joined value "foo,bar".
	// Listed matchers are evaluated by AND condition.
	// If OR matching condition is necessary, set the condition within a single matcher.
	// Default is not set.
	QueryMatchers []*ParamMatcherSpec `protobuf:"bytes,9,rep,name=QueryMatchers,json=queryMatchers,proto3" json:"QueryMatchers,omitempty"`
	// [OPTIONAL]
	// HashTableSize is the size of hash tables for hash-based load balancers.
	// This field is used by Maglev and RingHash load balancers.
	// If not set, default value is used.
	// Default value depends on the load balancer.
	HashTableSize int32 `protobuf:"varint,10,opt,name=HashTableSize,json=hashTableSize,proto3" json:"HashTableSize,omitempty"`
	// [OPTIONAL]
	// Hashers is the hashing methods for hash-based load balancers.
	// This field is optional but should be set at least 1
	// for hash-based load balancers.
	// Default is not set.
	Hashers       []*HTTPHasherSpec `protobuf:"bytes,11,rep,name=Hashers,json=hashers,proto3" json:"Hashers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadBalancerSpec) Reset() {
	*x = LoadBalancerSpec{}
	mi := &file_core_v1_httpproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerSpec) ProtoMessage() {}

func (x *LoadBalancerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_httpproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerSpec.ProtoReflect.Descriptor instead.
func (*LoadBalancerSpec) Descriptor() ([]byte, []int) {
	return file_core_v1_httpproxy_proto_rawDescGZIP(), []int{2}
}

func (x *LoadBalancerSpec) GetLBAlgorithm() LBAlgorithm {
	if x != nil {
		return x.LBAlgorithm
	}
	return LBAlgorithm_RoundRobin
}

func (x *LoadBalancerSpec) GetUpstreams() []*UpstreamSpec {
	if x != nil {
		return x.Upstreams
	}
	return nil
}

func (x *LoadBalancerSpec) GetPathMatcher() *PathMatcherSpec {
	if x != nil {
		return x.PathMatcher
	}
	return nil
}

func (x *LoadBalancerSpec) GetPathMatchers() []*PathMatcherSpec {
	if x != nil {
		return x.PathMatchers
	}
	return nil
}

func (x *LoadBalancerSpec) GetMethods() []HTTPMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *LoadBalancerSpec) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *LoadBalancerSpec) GetPathParamMatchers() []*ParamMatcherSpec {
	if x != nil {
		return x.PathParamMatchers
	}
	return nil
}

func (x *LoadBalancerSpec) GetHeaderMatchers() []*ParamMatcherSpec {
	if x != nil {
		return x.HeaderMatchers
	}
	return nil
}

func (x *LoadBalancerSpec) GetQueryMatchers() []*ParamMatcherSpec {
	if x != nil {
		return x.QueryMatchers
	}
	return nil
}

func (x *LoadBalancerSpec) GetHashTableSize() int32 {
	if x != nil {
		return x.HashTableSize
	}
	return 0
}

func (x *LoadBalancerSpec) GetHashers() []*HTTPHasherSpec {
	if x != nil {
		return x.Hashers
	}
	return nil
}

// PathMatcherSpec is the specification of PathMatcher object
// used for path matching of incoming HTTP requests.
type PathMatcherSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [OPTIONAL]
	// Match is the url path pattern to be matched to this matcher.
	// The grammar of the pattern depends on the MatchType.
	// This pattern should not contain prefix set by TrimPrefix or AppendPrefix.
	// Currently, only 1 prefix string can be set here.
	// Use Regex or RegexPOSIX match type and ser Rewrite field
	// if you need trim multiple prefix.
	// It can also trim or rewrite specific patterns.
	// Default is not set.
	Match string `protobuf:"bytes,1,opt,name=Match,json=match,proto3" json:"Match,omitempty"`
	// [OPTIONAL]
	// MatchType is the type of pattern matching algorithm.
	// The path pattern specified at the Match field should follow the
	// grammar of this match type.
	// Default is [Prefix].
	MatchType kernel.MatchType `protobuf:"varint,2,opt,name=MatchType,json=matchType,proto3,enum=kernel.MatchType" json:"MatchType,omitempty"`
	// [OPTIONAL]
	// Rewrite is the path rewrite expression.
	// This field is used when the MatchType is Regex or RegexPOSIX.
	// Checkout https://pkg.go.dev/regexp#Regexp.ExpandString
	// Default is not set.
	Rewrite string `protobuf:"bytes,3,opt,name=Rewrite,json=rewrite,proto3" json:"Rewrite,omitempty"`
	// [OPTIONAL]
	// TrimPrefix is the prefix string to be removed from the URL path.
	// For example, "/trim/me", "/prefix", "/api".
	// This prefix is removed before checking the match.
	// So the Match filed should not contain this value.
	// Default is not set.
	TrimPrefix string `protobuf:"bytes,4,opt,name=TrimPrefix,json=trimPrefix,proto3" json:"TrimPrefix,omitempty"`
	// [OPTIONAL]
	// AppendPrefix is the prefix string to be added to the URL path.
	// For example, "/append/me", "/prefix", "/api".
	// This prefix is added after checking the match.
	// So the Match filed should not contain this value.
	// Default is not set.
	AppendPrefix  string `protobuf:"bytes,5,opt,name=AppendPrefix,json=appendPrefix,proto3" json:"AppendPrefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathMatcherSpec) Reset() {
	*x = PathMatcherSpec{}
	mi := &file_core_v1_httpproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathMatcherSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathMatcherSpec) ProtoMessage() {}

func (x *PathMatcherSpec) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_httpproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathMatcherSpec.ProtoReflect.Descriptor instead.
func (*PathMatcherSpec) Descriptor() ([]byte, []int) {
	return file_core_v1_httpproxy_proto_rawDescGZIP(), []int{3}
}

func (x *PathMatcherSpec) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *PathMatcherSpec) GetMatchType() kernel.MatchType {
	if x != nil {
		return x.MatchType
	}
	return kernel.MatchType(0)
}

func (x *PathMatcherSpec) GetRewrite() string {
	if x != nil {
		return x.Rewrite
	}
	return ""
}

func (x *PathMatcherSpec) GetTrimPrefix() string {
	if x != nil {
		return x.TrimPrefix
	}
	return ""
}

func (x *PathMatcherSpec) GetAppendPrefix() string {
	if x != nil {
		return x.AppendPrefix
	}
	return ""
}

// ParamMatcherSpec is the specification of ParamMatcherParamMatcherSpec object
// used for header or query value matching.
type ParamMatcherSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [REQUIRED]
	// Key is the key name to check.
	// If the specified key were not found in header, query or path params,
	// this matcher fails without calling the match function specified at MatchType.
	// Default is not set.
	Key string `protobuf:"bytes,1,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	// [OPTIONAL]
	// Patterns is the value pattern list.
	// The grammar of the pattern depends on the MatchType.
	// Patterns are evaluated by OR condition.
	// It will be considered that at least 1 pattern matched to a target,
	// this macher object returns true.
	// Default is not set, which means an empty string.
	Patterns []string `protobuf:"bytes,2,rep,name=Patterns,json=patterns,proto3" json:"Patterns,omitempty"`
	// [OPTIONAL]
	// MatchType is the type of pattern matching algorithm.
	// The pattern specified at the Pattern field should follow the
	// grammar of this match type.
	// Default is [Exact].
	MatchType     kernel.MatchType `protobuf:"varint,3,opt,name=MatchType,json=matchType,proto3,enum=kernel.MatchType" json:"MatchType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamMatcherSpec) Reset() {
	*x = ParamMatcherSpec{}
	mi := &file_core_v1_httpproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamMatcherSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamMatcherSpec) ProtoMessage() {}

func (x *ParamMatcherSpec) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_httpproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamMatcherSpec.ProtoReflect.Descriptor instead.
func (*ParamMatcherSpec) Descriptor() ([]byte, []int) {
	return file_core_v1_httpproxy_proto_rawDescGZIP(), []int{4}
}

func (x *ParamMatcherSpec) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ParamMatcherSpec) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *ParamMatcherSpec) GetMatchType() kernel.MatchType {
	if x != nil {
		return x.MatchType
	}
	return kernel.MatchType(0)
}

// UpstreamSpec is the specification of Upstream object.
type UpstreamSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [REQUIRED]
	// URL is the base url for for proxy.
	// This field can contain URL path.
	// For example "http://localhost:8080/api/"
	// Default is not set.
	URL string `protobuf:"bytes,1,opt,name=URL,json=url,proto3" json:"URL,omitempty"`
	// [OPTIONAL]
	// Weight is the weight, or priority of this target.
	// Set -1 to disable this upstream.
	// 0 is the same as default value 1.
	// Default is [1].
	Weight int32 `protobuf:"varint,2,opt,name=Weight,json=weight,proto3" json:"Weight,omitempty"`
	// [OPTIONAL]
	// EnablePassive enables passive health check.
	// Default is [false].
	EnablePassive bool `protobuf:"varint,3,opt,name=EnablePassive,json=enablePassive,proto3" json:"EnablePassive,omitempty"`
	// [OPTIONAL]
	// EnableActive enables active health check.
	// Default is [false].
	EnableActive bool `protobuf:"varint,4,opt,name=EnableActive,json=enableActive,proto3" json:"EnableActive,omitempty"`
	// [OPTIONAL]
	// InitialDelay is the wait time in seconds until to start active health checking after starts.
	// Note that this field is used only when the active health checking is configured.
	// Default is [0].
	InitialDelay int32 `protobuf:"varint,7,opt,name=InitialDelay,json=initialDelay,proto3" json:"InitialDelay,omitempty"`
	// [OPTIONAL]
	// CheckInterval is the interval of active health check in seconds.
	// Note that this field is used only when the active health checking is configured.
	// Default is [1].
	CheckInterval int32 `protobuf:"varint,8,opt,name=CheckInterval,json=checkInterval,proto3" json:"CheckInterval,omitempty"`
	// [OPTIONAL]
	// NetworkType is network type used for active health cheking.
	// Note that this field is used only when the active health checking is configured.
	// Default is [HTTP].
	NetworkType kernel.NetworkType `protobuf:"varint,9,opt,name=NetworkType,json=networkType,proto3,enum=kernel.NetworkType" json:"NetworkType,omitempty"`
	// [OPTIONAL]
	// Protocol is the protocol number or a protocol name used for health checking.
	// This field is used when "IP", "IP4" or "IP6" is selected as the network type.
	// See https://pkg.go.dev/net#Dial for more detail.
	// Default is ["icmp"].
	Protocol string `protobuf:"bytes,10,opt,name=Protocol,json=protocol,proto3" json:"Protocol,omitempty"`
	// [OPTIONAL]
	// Address is the target IP address or URL for active health checking.
	// For example, specify a url "http://example.com/healthy" for HTTP network type,
	// "127.0.0.1:8080" for TCP and UDP type, "127.0.0.1" for IP type.
	// See https://pkg.go.dev/net#Dial for more detail.
	// Default is not set.
	Address string `protobuf:"bytes,11,opt,name=Address,json=address,proto3" json:"Address,omitempty"`
	// [OPTIONAL]
	// [This feature is disabled now]
	// CircuitBreaker is circuit breaker specification for health checking.
	// Default values are used when not specified.
	CircuitBreaker *CircuitBreaker `protobuf:"bytes,12,opt,name=CircuitBreaker,json=circuitBreaker,proto3" json:"CircuitBreaker,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpstreamSpec) Reset() {
	*x = UpstreamSpec{}
	mi := &file_core_v1_httpproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamSpec) ProtoMessage() {}

func (x *UpstreamSpec) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_httpproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamSpec.ProtoReflect.Descriptor instead.
func (*UpstreamSpec) Descriptor() ([]byte, []int) {
	return file_core_v1_httpproxy_proto_rawDescGZIP(), []int{5}
}

func (x *UpstreamSpec) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *UpstreamSpec) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpstreamSpec) GetEnablePassive() bool {
	if x != nil {
		return x.EnablePassive
	}
	return false
}

func (x *UpstreamSpec) GetEnableActive() bool {
	if x != nil {
		return x.EnableActive
	}
	return false
}

func (x *UpstreamSpec) GetInitialDelay() int32 {
	if x != nil {
		return x.InitialDelay
	}
	return 0
}

func (x *UpstreamSpec) GetCheckInterval() int32 {
	if x != nil {
		return x.CheckInterval
	}
	return 0
}

func (x *UpstreamSpec) GetNetworkType() kernel.NetworkType {
	if x != nil {
		return x.NetworkType
	}
	return kernel.NetworkType(0)
}

func (x *UpstreamSpec) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *UpstreamSpec) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpstreamSpec) GetCircuitBreaker() *CircuitBreaker {
	if x != nil {
		return x.CircuitBreaker
	}
	return nil
}

// CircuitBreaker is the specification of CircuitBreaker object.
type CircuitBreaker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [OPTIONAL]
	// FailureThreshold is the threshold to consider upstream unhealthy.
	// The unit of the value differs depending on  the count algorithm.
	// The unit is count for ConsecutiveCounter and percentage 0-100 for others.
	// Default is [5].
	FailureThreshold int32 `protobuf:"varint,1,opt,name=FailureThreshold,json=failureThreshold,proto3" json:"FailureThreshold,omitempty"`
	// [OPTIONAL]
	// SuccessThreshold is the threshold to consider upstream healthy.
	// The unit of the value differs depending on  the count algorithm.
	// The unit is count for ConsecutiveCounter and percentage 0-100 for others.
	// Default is [80].
	SuccessThreshold int32 `protobuf:"varint,2,opt,name=SuccessThreshold,json=successThreshold,proto3" json:"SuccessThreshold,omitempty"`
	// [OPTIONAL]
	// EffectiveFailureSamples is the number of health check samples that is
	// considered to be meaningful for calculating failure rate.
	// The default value of 20 means that the initial 20 requests are
	// accepted after the status of circuit breaker changed to closed
	// inspite of the failure rate.
	// Ths value will be ignored for ConsecutiveCounter.
	// Default is [20].
	EffectiveFailureSamples int32 `protobuf:"varint,3,opt,name=EffectiveFailureSamples,json=effectiveFailureSamples,proto3" json:"EffectiveFailureSamples,omitempty"`
	// [OPTIONAL]
	// EffectiveSuccessSamples is the number of health check samples that is
	// considered to be meaningful for calculating success rate
	// when the status of circuit breaker is .
	// The default value of 20 means that the initial 20 requests are
	// accepted after the status of circuit breaker changed to closed
	// inspite of the failure rate.
	// Ths value will be ignored for ConsecutiveCounter.
	// Default is [20].
	EffectiveSuccessSamples int32 `protobuf:"varint,4,opt,name=EffectiveSuccessSamples,json=effectiveSuccessSamples,proto3" json:"EffectiveSuccessSamples,omitempty"`
	// [OPTIONAL]
	// WaitDuration is wait time to reset success and failure count
	// of circuit breaker in seconds.
	// Default is [180], or 3 minutes.
	WaitDuration int32 `protobuf:"varint,5,opt,name=WaitDuration,json=waitDuration,proto3" json:"WaitDuration,omitempty"`
	// [OPTIONAL]
	// CircuitBreakerCounter is the success and failure counter of health cheking for circuit breaker.
	// ConsecutiveCounter is set by default.
	// Currently, these configs do not work.
	//
	// Types that are valid to be assigned to CircuitBreakerCounter:
	//
	//	*CircuitBreaker_ConsecutiveCounter
	//	*CircuitBreaker_CountBasedFixedWindowCounter
	//	*CircuitBreaker_TimeBasedFixedWindowCounter
	//	*CircuitBreaker_CountBasedSlidingWindowCounter
	//	*CircuitBreaker_TimeBasedSlidingWindowCounter
	CircuitBreakerCounter isCircuitBreaker_CircuitBreakerCounter `protobuf_oneof:"CircuitBreakerCounter"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CircuitBreaker) Reset() {
	*x = CircuitBreaker{}
	mi := &file_core_v1_httpproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitBreaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitBreaker) ProtoMessage() {}

func (x *CircuitBreaker) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_httpproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitBreaker.ProtoReflect.Descriptor instead.
func (*CircuitBreaker) Descriptor() ([]byte, []int) {
	return file_core_v1_httpproxy_proto_rawDescGZIP(), []int{6}
}

func (x *CircuitBreaker) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *CircuitBreaker) GetSuccessThreshold() int32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

func (x *CircuitBreaker) GetEffectiveFailureSamples() int32 {
	if x != nil {
		return x.EffectiveFailureSamples
	}
	return 0
}

func (x *CircuitBreaker) GetEffectiveSuccessSamples() int32 {
	if x != nil {
		return x.EffectiveSuccessSamples
	}
	return 0
}

func (x *CircuitBreaker) GetWaitDuration() int32 {
	if x != nil {
		return x.WaitDuration
	}
	return 0
}

func (x *CircuitBreaker) GetCircuitBreakerCounter() isCircuitBreaker_CircuitBreakerCounter {
	if x != nil {
		return x.CircuitBreakerCounter
	}
	return nil
}

func (x *CircuitBreaker) GetConsecutiveCounter() *ConsecutiveCounterSpec {
	if x != nil {
		if x, ok := x.CircuitBreakerCounter.(*CircuitBreaker_ConsecutiveCounter); ok {
			return x.ConsecutiveCounter
		}
	}
	return nil
}

func (x *CircuitBreaker) GetCountBasedFixedWindowCounter() *CountBasedFixedWindowCounterSpec {
	if x != nil {
		if x, ok := x.CircuitBreakerCounter.(*CircuitBreaker_CountBasedFixedWindowCounter); ok {
			return x.CountBasedFixedWindowCounter
		}
	}
	return nil
}

func (x *CircuitBreaker) GetTimeBasedFixedWindowCounter() *TimeBasedFixedWindowCounterSpec {
	if x != nil {
		if x, ok := x.CircuitBreakerCounter.(*CircuitBreaker_TimeBasedFixedWindowCounter); ok {
			return x.TimeBasedFixedWindowCounter
		}
	}
	return nil
}

func (x *CircuitBreaker) GetCountBasedSlidingWindowCounter() *CountBasedSlidingWindowCounterSpec {
	if x != nil {
		if x, ok := x.CircuitBreakerCounter.(*CircuitBreaker_CountBasedSlidingWindowCounter); ok {
			return x.CountBasedSlidingWindowCounter
		}
	}
	return nil
}

func (x *CircuitBreaker) GetTimeBasedSlidingWindowCounter() *TimeBasedSlidingWindowCounterSpec {
	if x != nil {
		if x, ok := x.CircuitBreakerCounter.(*CircuitBreaker_TimeBasedSlidingWindowCounter); ok {
			return x.TimeBasedSlidingWindowCounter
		}
	}
	return nil
}

type isCircuitBreaker_CircuitBreakerCounter interface {
	isCircuitBreaker_CircuitBreakerCounter()
}

type CircuitBreaker_ConsecutiveCounter struct {
	ConsecutiveCounter *ConsecutiveCounterSpec `protobuf:"bytes,6,opt,name=ConsecutiveCounter,json=consecutiveCounter,proto3,oneof"`
}

type CircuitBreaker_CountBasedFixedWindowCounter struct {
	CountBasedFixedWindowCounter *CountBasedFixedWindowCounterSpec `protobuf:"bytes,7,opt,name=CountBasedFixedWindowCounter,json=countBasedFixedWindowCounter,proto3,oneof"`
}

type CircuitBreaker_TimeBasedFixedWindowCounter struct {
	TimeBasedFixedWindowCounter *TimeBasedFixedWindowCounterSpec `protobuf:"bytes,8,opt,name=TimeBasedFixedWindowCounter,json=timeBasedFixedWindowCounter,proto3,oneof"`
}

type CircuitBreaker_CountBasedSlidingWindowCounter struct {
	CountBasedSlidingWindowCounter *CountBasedSlidingWindowCounterSpec `protobuf:"bytes,9,opt,name=CountBasedSlidingWindowCounter,json=countBasedSlidingWindowCounter,proto3,oneof"`
}

type CircuitBreaker_TimeBasedSlidingWindowCounter struct {
	TimeBasedSlidingWindowCounter *TimeBasedSlidingWindowCounterSpec `protobuf:"bytes,10,opt,name=TimeBasedSlidingWindowCounter,json=timeBasedSlidingWindowCounter,proto3,oneof"`
}

func (*CircuitBreaker_ConsecutiveCounter) isCircuitBreaker_CircuitBreakerCounter() {}

func (*CircuitBreaker_CountBasedFixedWindowCounter) isCircuitBreaker_CircuitBreakerCounter() {}

func (*CircuitBreaker_TimeBasedFixedWindowCounter) isCircuitBreaker_CircuitBreakerCounter() {}

func (*CircuitBreaker_CountBasedSlidingWindowCounter) isCircuitBreaker_CircuitBreakerCounter() {}

func (*CircuitBreaker_TimeBasedSlidingWindowCounter) isCircuitBreaker_CircuitBreakerCounter() {}

// ConsecutiveCounterSpec is the specification of the circuit breaker counter
// with consecutive counting algorithm.
type ConsecutiveCounterSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsecutiveCounterSpec) Reset() {
	*x = ConsecutiveCounterSpec{}
	mi := &file_core_v1_httpproxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsecutiveCounterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsecutiveCounterSpec) ProtoMessage() {}

func (x *ConsecutiveCounterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_httpproxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsecutiveCounterSpec.ProtoReflect.Descriptor instead.
func (*ConsecutiveCounterSpec) Descriptor() ([]byte, []int) {
	return file_core_v1_httpproxy_proto_rawDescGZIP(), []int{7}
}

// CountBasedFixedWindowCounterSpec is the specification of the circuit breaker counter
// with count-based fixed window algorithm.
type CountBasedFixedWindowCounterSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [REQUIRED]
	// This value must be grater than or equal to effectiveFailureSamples and effectiveSuccessSamples.
	Samples       int32 `protobuf:"varint,1,opt,name=Samples,json=samples,proto3" json:"Samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountBasedFixedWindowCounterSpec) Reset() {
	*x = CountBasedFixedWindowCounterSpec{}
	mi := &file_core_v1_httpproxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountBasedFixedWindowCounterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountBasedFixedWindowCounterSpec) ProtoMessage() {}

func (x *CountBasedFixedWindowCounterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_httpproxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountBasedFixedWindowCounterSpec.ProtoReflect.Descriptor instead.
func (*CountBasedFixedWindowCounterSpec) Descriptor() ([]byte, []int) {
	return file_core_v1_httpproxy_proto_rawDescGZIP(), []int{8}
}

func (x *CountBasedFixedWindowCounterSpec) GetSamples() int32 {
	if x != nil {
		return x.Samples
	}
	return 0
}

// TimeBasedFixedWindowCounterSpec is the specification of the circuit breaker counter
// with time-based fixed window algorithm.
type TimeBasedFixedWindowCounterSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [OPTIONAL]
	// Window width in seconds.
	// Default is [5].
	WindowWidth   int32 `protobuf:"varint,1,opt,name=WindowWidth,json=windowWidth,proto3" json:"WindowWidth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeBasedFixedWindowCounterSpec) Reset() {
	*x = TimeBasedFixedWindowCounterSpec{}
	mi := &file_core_v1_httpproxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeBasedFixedWindowCounterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeBasedFixedWindowCounterSpec) ProtoMessage() {}

func (x *TimeBasedFixedWindowCounterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_httpproxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeBasedFixedWindowCounterSpec.ProtoReflect.Descriptor instead.
func (*TimeBasedFixedWindowCounterSpec) Descriptor() ([]byte, []int) {
	return file_core_v1_httpproxy_proto_rawDescGZIP(), []int{9}
}

func (x *TimeBasedFixedWindowCounterSpec) GetWindowWidth() int32 {
	if x != nil {
		return x.WindowWidth
	}
	return 0
}

// CountBasedSlidingWindowCounterSpec is the specification of the circuit breaker counter
// with count-based sliding window algorithm.
type CountBasedSlidingWindowCounterSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [REQUIRED]
	// This value must be grater than or equal to effectiveFailureSamples and effectiveSuccessSamples.
	Samples int32 `protobuf:"varint,1,opt,name=Samples,json=samples,proto3" json:"Samples,omitempty"`
	// [REQUIRED]
	HistoryLimit  int32 `protobuf:"varint,2,opt,name=HistoryLimit,json=historyLimit,proto3" json:"HistoryLimit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountBasedSlidingWindowCounterSpec) Reset() {
	*x = CountBasedSlidingWindowCounterSpec{}
	mi := &file_core_v1_httpproxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountBasedSlidingWindowCounterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountBasedSlidingWindowCounterSpec) ProtoMessage() {}

func (x *CountBasedSlidingWindowCounterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_httpproxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountBasedSlidingWindowCounterSpec.ProtoReflect.Descriptor instead.
func (*CountBasedSlidingWindowCounterSpec) Descriptor() ([]byte, []int) {
	return file_core_v1_httpproxy_proto_rawDescGZIP(), []int{10}
}

func (x *CountBasedSlidingWindowCounterSpec) GetSamples() int32 {
	if x != nil {
		return x.Samples
	}
	return 0
}

func (x *CountBasedSlidingWindowCounterSpec) GetHistoryLimit() int32 {
	if x != nil {
		return x.HistoryLimit
	}
	return 0
}

// TimeBasedSlidingWindowCounterSpec is the specification of the circuit breaker counter
// with time-based sliding window algorithm.
type TimeBasedSlidingWindowCounterSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [OPTIONAL]
	// Window width in seconds.
	// Default is [5].
	WindowWidth int32 `protobuf:"varint,1,opt,name=WindowWidth,json=windowWidth,proto3" json:"WindowWidth,omitempty"`
	// [REQUIRED]
	HistoryLimit  int32 `protobuf:"varint,2,opt,name=HistoryLimit,json=historyLimit,proto3" json:"HistoryLimit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeBasedSlidingWindowCounterSpec) Reset() {
	*x = TimeBasedSlidingWindowCounterSpec{}
	mi := &file_core_v1_httpproxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeBasedSlidingWindowCounterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeBasedSlidingWindowCounterSpec) ProtoMessage() {}

func (x *TimeBasedSlidingWindowCounterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_httpproxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeBasedSlidingWindowCounterSpec.ProtoReflect.Descriptor instead.
func (*TimeBasedSlidingWindowCounterSpec) Descriptor() ([]byte, []int) {
	return file_core_v1_httpproxy_proto_rawDescGZIP(), []int{11}
}

func (x *TimeBasedSlidingWindowCounterSpec) GetWindowWidth() int32 {
	if x != nil {
		return x.WindowWidth
	}
	return 0
}

func (x *TimeBasedSlidingWindowCounterSpec) GetHistoryLimit() int32 {
	if x != nil {
		return x.HistoryLimit
	}
	return 0
}

var File_core_v1_httpproxy_proto protoreflect.FileDescriptor

const file_core_v1_httpproxy_proto_rawDesc = "" +
	"\n" +
	"\x17core/v1/httpproxy.proto\x12\acore.v1\x1a\x1bbuf/validate/validate.proto\x1a\x12core/v1/http.proto\x1a\x18core/v1/resilience.proto\x1a\x14kernel/network.proto\x1a\x15kernel/resource.proto\x1a\x14kernel/txtutil.proto\"\xd9\x01\n" +
	"\x13ReverseProxyHandler\x12.\n" +
	"\n" +
	"APIVersion\x18\x01 \x01(\tB\x0e\xbaH\vr\t\n" +
	"\acore/v1R\n" +
	"apiVersion\x12.\n" +
	"\x04Kind\x18\x02 \x01(\tB\x1a\xbaH\x17r\x15\n" +
	"\x13ReverseProxyHandlerR\x04kind\x12,\n" +
	"\bMetadata\x18\x03 \x01(\v2\x10.kernel.MetadataR\bmetadata\x124\n" +
	"\x04Spec\x18\x04 \x01(\v2 .core.v1.ReverseProxyHandlerSpecR\x04spec\"\xde\x02\n" +
	"\x17ReverseProxyHandlerSpec\x125\n" +
	"\fErrorHandler\x18\x01 \x01(\v2\x11.kernel.ReferenceR\ferrorHandler\x12$\n" +
	"\bPatterns\x18\x02 \x03(\tB\b\xbaH\x05\x92\x01\x02\x18\x01R\bpatterns\x127\n" +
	"\aMethods\x18\x03 \x03(\x0e2\x13.core.v1.HTTPMethodB\b\xbaH\x05\x92\x01\x02\x18\x01R\amethods\x125\n" +
	"\fTripperwares\x18\x04 \x03(\v2\x11.kernel.ReferenceR\ftripperwares\x125\n" +
	"\fRoundTripper\x18\x05 \x01(\v2\x11.kernel.ReferenceR\froundTripper\x12?\n" +
	"\rLoadBalancers\x18\x06 \x03(\v2\x19.core.v1.LoadBalancerSpecR\rloadBalancers\"\xf8\x04\n" +
	"\x10LoadBalancerSpec\x126\n" +
	"\vLBAlgorithm\x18\x01 \x01(\x0e2\x14.core.v1.LBAlgorithmR\vlbAlgorithm\x123\n" +
	"\tUpstreams\x18\x02 \x03(\v2\x15.core.v1.UpstreamSpecR\tupstreams\x12:\n" +
	"\vPathMatcher\x18\x03 \x01(\v2\x18.core.v1.PathMatcherSpecR\vpathMatcher\x12<\n" +
	"\fPathMatchers\x18\x04 \x03(\v2\x18.core.v1.PathMatcherSpecR\fpathMatchers\x127\n" +
	"\aMethods\x18\x05 \x03(\x0e2\x13.core.v1.HTTPMethodB\b\xbaH\x05\x92\x01\x02\x18\x01R\amethods\x12\x1e\n" +
	"\x05Hosts\x18\x06 \x03(\tB\b\xbaH\x05\x92\x01\x02\x18\x01R\x05hosts\x12G\n" +
	"\x11PathParamMatchers\x18\a \x03(\v2\x19.core.v1.ParamMatcherSpecR\x11pathParamMatchers\x12A\n" +
	"\x0eHeaderMatchers\x18\b \x03(\v2\x19.core.v1.ParamMatcherSpecR\x0eheaderMatchers\x12?\n" +
	"\rQueryMatchers\x18\t \x03(\v2\x19.core.v1.ParamMatcherSpecR\rqueryMatchers\x12$\n" +
	"\rHashTableSize\x18\n" +
	" \x01(\x05R\rhashTableSize\x121\n" +
	"\aHashers\x18\v \x03(\v2\x17.core.v1.HTTPHasherSpecR\ahashers\"\xb6\x01\n" +
	"\x0fPathMatcherSpec\x12\x14\n" +
	"\x05Match\x18\x01 \x01(\tR\x05match\x12/\n" +
	"\tMatchType\x18\x02 \x01(\x0e2\x11.kernel.MatchTypeR\tmatchType\x12\x18\n" +
	"\aRewrite\x18\x03 \x01(\tR\arewrite\x12\x1e\n" +
	"\n" +
	"TrimPrefix\x18\x04 \x01(\tR\n" +
	"trimPrefix\x12\"\n" +
	"\fAppendPrefix\x18\x05 \x01(\tR\fappendPrefix\"z\n" +
	"\x10ParamMatcherSpec\x12\x19\n" +
	"\x03Key\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03key\x12\x1a\n" +
	"\bPatterns\x18\x02 \x03(\tR\bpatterns\x12/\n" +
	"\tMatchType\x18\x03 \x01(\x0e2\x11.kernel.MatchTypeR\tmatchType\"\xac\x03\n" +
	"\fUpstreamSpec\x12-\n" +
	"\x03URL\x18\x01 \x01(\tB\x1b\xbaH\x18r\x162\x14(http://|https://).*R\x03url\x12+\n" +
	"\x06Weight\x18\x02 \x01(\x05B\x13\xbaH\x10\x1a\x0e\x18\xe8\a(\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x06weight\x12$\n" +
	"\rEnablePassive\x18\x03 \x01(\bR\renablePassive\x12\"\n" +
	"\fEnableActive\x18\x04 \x01(\bR\fenableActive\x12\"\n" +
	"\fInitialDelay\x18\a \x01(\x05R\finitialDelay\x12$\n" +
	"\rCheckInterval\x18\b \x01(\x05R\rcheckInterval\x125\n" +
	"\vNetworkType\x18\t \x01(\x0e2\x13.kernel.NetworkTypeR\vnetworkType\x12\x1a\n" +
	"\bProtocol\x18\n" +
	" \x01(\tR\bprotocol\x12\x18\n" +
	"\aAddress\x18\v \x01(\tR\aaddress\x12?\n" +
	"\x0eCircuitBreaker\x18\f \x01(\v2\x17.core.v1.CircuitBreakerR\x0ecircuitBreaker\"\xe3\x06\n" +
	"\x0eCircuitBreaker\x123\n" +
	"\x10FailureThreshold\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x10failureThreshold\x123\n" +
	"\x10SuccessThreshold\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x10successThreshold\x12A\n" +
	"\x17EffectiveFailureSamples\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x17effectiveFailureSamples\x12A\n" +
	"\x17EffectiveSuccessSamples\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x17effectiveSuccessSamples\x12+\n" +
	"\fWaitDuration\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\fwaitDuration\x12Q\n" +
	"\x12ConsecutiveCounter\x18\x06 \x01(\v2\x1f.core.v1.ConsecutiveCounterSpecH\x00R\x12consecutiveCounter\x12o\n" +
	"\x1cCountBasedFixedWindowCounter\x18\a \x01(\v2).core.v1.CountBasedFixedWindowCounterSpecH\x00R\x1ccountBasedFixedWindowCounter\x12l\n" +
	"\x1bTimeBasedFixedWindowCounter\x18\b \x01(\v2(.core.v1.TimeBasedFixedWindowCounterSpecH\x00R\x1btimeBasedFixedWindowCounter\x12u\n" +
	"\x1eCountBasedSlidingWindowCounter\x18\t \x01(\v2+.core.v1.CountBasedSlidingWindowCounterSpecH\x00R\x1ecountBasedSlidingWindowCounter\x12r\n" +
	"\x1dTimeBasedSlidingWindowCounter\x18\n" +
	" \x01(\v2*.core.v1.TimeBasedSlidingWindowCounterSpecH\x00R\x1dtimeBasedSlidingWindowCounterB\x17\n" +
	"\x15CircuitBreakerCounter\"\x18\n" +
	"\x16ConsecutiveCounterSpec\"E\n" +
	" CountBasedFixedWindowCounterSpec\x12!\n" +
	"\aSamples\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\asamples\"L\n" +
	"\x1fTimeBasedFixedWindowCounterSpec\x12)\n" +
	"\vWindowWidth\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\vwindowWidth\"t\n" +
	"\"CountBasedSlidingWindowCounterSpec\x12!\n" +
	"\aSamples\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\asamples\x12+\n" +
	"\fHistoryLimit\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\fhistoryLimit\"{\n" +
	"!TimeBasedSlidingWindowCounterSpec\x12)\n" +
	"\vWindowWidth\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\vwindowWidth\x12+\n" +
	"\fHistoryLimit\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\fhistoryLimitB9Z7github.com/aileron-gateway/aileron-gateway/apis/core/v1b\x06proto3"

var (
	file_core_v1_httpproxy_proto_rawDescOnce sync.Once
	file_core_v1_httpproxy_proto_rawDescData []byte
)

func file_core_v1_httpproxy_proto_rawDescGZIP() []byte {
	file_core_v1_httpproxy_proto_rawDescOnce.Do(func() {
		file_core_v1_httpproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_httpproxy_proto_rawDesc), len(file_core_v1_httpproxy_proto_rawDesc)))
	})
	return file_core_v1_httpproxy_proto_rawDescData
}

var file_core_v1_httpproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_core_v1_httpproxy_proto_goTypes = []any{
	(*ReverseProxyHandler)(nil),                // 0: core.v1.ReverseProxyHandler
	(*ReverseProxyHandlerSpec)(nil),            // 1: core.v1.ReverseProxyHandlerSpec
	(*LoadBalancerSpec)(nil),                   // 2: core.v1.LoadBalancerSpec
	(*PathMatcherSpec)(nil),                    // 3: core.v1.PathMatcherSpec
	(*ParamMatcherSpec)(nil),                   // 4: core.v1.ParamMatcherSpec
	(*UpstreamSpec)(nil),                       // 5: core.v1.UpstreamSpec
	(*CircuitBreaker)(nil),                     // 6: core.v1.CircuitBreaker
	(*ConsecutiveCounterSpec)(nil),             // 7: core.v1.ConsecutiveCounterSpec
	(*CountBasedFixedWindowCounterSpec)(nil),   // 8: core.v1.CountBasedFixedWindowCounterSpec
	(*TimeBasedFixedWindowCounterSpec)(nil),    // 9: core.v1.TimeBasedFixedWindowCounterSpec
	(*CountBasedSlidingWindowCounterSpec)(nil), // 10: core.v1.CountBasedSlidingWindowCounterSpec
	(*TimeBasedSlidingWindowCounterSpec)(nil),  // 11: core.v1.TimeBasedSlidingWindowCounterSpec
	(*kernel.Metadata)(nil),                    // 12: kernel.Metadata
	(*kernel.Reference)(nil),                   // 13: kernel.Reference
	(HTTPMethod)(0),                            // 14: core.v1.HTTPMethod
	(LBAlgorithm)(0),                           // 15: core.v1.LBAlgorithm
	(*HTTPHasherSpec)(nil),                     // 16: core.v1.HTTPHasherSpec
	(kernel.MatchType)(0),                      // 17: kernel.MatchType
	(kernel.NetworkType)(0),                    // 18: kernel.NetworkType
}
var file_core_v1_httpproxy_proto_depIdxs = []int32{
	12, // 0: core.v1.ReverseProxyHandler.Metadata:type_name -> kernel.Metadata
	1,  // 1: core.v1.ReverseProxyHandler.Spec:type_name -> core.v1.ReverseProxyHandlerSpec
	13, // 2: core.v1.ReverseProxyHandlerSpec.ErrorHandler:type_name -> kernel.Reference
	14, // 3: core.v1.ReverseProxyHandlerSpec.Methods:type_name -> core.v1.HTTPMethod
	13, // 4: core.v1.ReverseProxyHandlerSpec.Tripperwares:type_name -> kernel.Reference
	13, // 5: core.v1.ReverseProxyHandlerSpec.RoundTripper:type_name -> kernel.Reference
	2,  // 6: core.v1.ReverseProxyHandlerSpec.LoadBalancers:type_name -> core.v1.LoadBalancerSpec
	15, // 7: core.v1.LoadBalancerSpec.LBAlgorithm:type_name -> core.v1.LBAlgorithm
	5,  // 8: core.v1.LoadBalancerSpec.Upstreams:type_name -> core.v1.UpstreamSpec
	3,  // 9: core.v1.LoadBalancerSpec.PathMatcher:type_name -> core.v1.PathMatcherSpec
	3,  // 10: core.v1.LoadBalancerSpec.PathMatchers:type_name -> core.v1.PathMatcherSpec
	14, // 11: core.v1.LoadBalancerSpec.Methods:type_name -> core.v1.HTTPMethod
	4,  // 12: core.v1.LoadBalancerSpec.PathParamMatchers:type_name -> core.v1.ParamMatcherSpec
	4,  // 13: core.v1.LoadBalancerSpec.HeaderMatchers:type_name -> core.v1.ParamMatcherSpec
	4,  // 14: core.v1.LoadBalancerSpec.QueryMatchers:type_name -> core.v1.ParamMatcherSpec
	16, // 15: core.v1.LoadBalancerSpec.Hashers:type_name -> core.v1.HTTPHasherSpec
	17, // 16: core.v1.PathMatcherSpec.MatchType:type_name -> kernel.MatchType
	17, // 17: core.v1.ParamMatcherSpec.MatchType:type_name -> kernel.MatchType
	18, // 18: core.v1.UpstreamSpec.NetworkType:type_name -> kernel.NetworkType
	6,  // 19: core.v1.UpstreamSpec.CircuitBreaker:type_name -> core.v1.CircuitBreaker
	7,  // 20: core.v1.CircuitBreaker.ConsecutiveCounter:type_name -> core.v1.ConsecutiveCounterSpec
	8,  // 21: core.v1.CircuitBreaker.CountBasedFixedWindowCounter:type_name -> core.v1.CountBasedFixedWindowCounterSpec
	9,  // 22: core.v1.CircuitBreaker.TimeBasedFixedWindowCounter:type_name -> core.v1.TimeBasedFixedWindowCounterSpec
	10, // 23: core.v1.CircuitBreaker.CountBasedSlidingWindowCounter:type_name -> core.v1.CountBasedSlidingWindowCounterSpec
	11, // 24: core.v1.CircuitBreaker.TimeBasedSlidingWindowCounter:type_name -> core.v1.TimeBasedSlidingWindowCounterSpec
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_core_v1_httpproxy_proto_init() }
func file_core_v1_httpproxy_proto_init() {
	if File_core_v1_httpproxy_proto != nil {
		return
	}
	file_core_v1_http_proto_init()
	file_core_v1_resilience_proto_init()
	file_core_v1_httpproxy_proto_msgTypes[6].OneofWrappers = []any{
		(*CircuitBreaker_ConsecutiveCounter)(nil),
		(*CircuitBreaker_CountBasedFixedWindowCounter)(nil),
		(*CircuitBreaker_TimeBasedFixedWindowCounter)(nil),
		(*CircuitBreaker_CountBasedSlidingWindowCounter)(nil),
		(*CircuitBreaker_TimeBasedSlidingWindowCounter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_httpproxy_proto_rawDesc), len(file_core_v1_httpproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_v1_httpproxy_proto_goTypes,
		DependencyIndexes: file_core_v1_httpproxy_proto_depIdxs,
		MessageInfos:      file_core_v1_httpproxy_proto_msgTypes,
	}.Build()
	File_core_v1_httpproxy_proto = out.File
	file_core_v1_httpproxy_proto_goTypes = nil
	file_core_v1_httpproxy_proto_depIdxs = nil
}
