// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: core/v1/template.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	kernel "github.com/aileron-gateway/aileron-gateway/apis/kernel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// + TemplateType
// TemplateType is the type of template document.
type TemplateType int32

const (
	TemplateType_Text   TemplateType = 0 // Text is a standard text type. Content will be used as it is.
	TemplateType_GoText TemplateType = 1 // GoText is Go's text template type. See https://pkg.go.dev/text/template.
	TemplateType_GoHTML TemplateType = 2 // GoHTML is Go's HTML template type. See https://pkg.go.dev/html/template.
)

// Enum value maps for TemplateType.
var (
	TemplateType_name = map[int32]string{
		0: "Text",
		1: "GoText",
		2: "GoHTML",
	}
	TemplateType_value = map[string]int32{
		"Text":   0,
		"GoText": 1,
		"GoHTML": 2,
	}
)

func (x TemplateType) Enum() *TemplateType {
	p := new(TemplateType)
	*p = x
	return p
}

func (x TemplateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_v1_template_proto_enumTypes[0].Descriptor()
}

func (TemplateType) Type() protoreflect.EnumType {
	return &file_core_v1_template_proto_enumTypes[0]
}

func (x TemplateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateType.Descriptor instead.
func (TemplateType) EnumDescriptor() ([]byte, []int) {
	return file_core_v1_template_proto_rawDescGZIP(), []int{0}
}

// + TemplateHandler
type TemplateHandler struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	APIVersion    string                 `protobuf:"bytes,1,opt,name=APIVersion,json=apiVersion,proto3" json:"APIVersion,omitempty"` // "core/v1"
	Kind          string                 `protobuf:"bytes,2,opt,name=Kind,json=kind,proto3" json:"Kind,omitempty"`                   // "TemplateHandler"
	Metadata      *kernel.Metadata       `protobuf:"bytes,3,opt,name=Metadata,json=metadata,proto3" json:"Metadata,omitempty"`
	Spec          *TemplateHandlerSpec   `protobuf:"bytes,4,opt,name=Spec,json=spec,proto3" json:"Spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateHandler) Reset() {
	*x = TemplateHandler{}
	mi := &file_core_v1_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateHandler) ProtoMessage() {}

func (x *TemplateHandler) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateHandler.ProtoReflect.Descriptor instead.
func (*TemplateHandler) Descriptor() ([]byte, []int) {
	return file_core_v1_template_proto_rawDescGZIP(), []int{0}
}

func (x *TemplateHandler) GetAPIVersion() string {
	if x != nil {
		return x.APIVersion
	}
	return ""
}

func (x *TemplateHandler) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TemplateHandler) GetMetadata() *kernel.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TemplateHandler) GetSpec() *TemplateHandlerSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// + TemplateHandlerSpec
type TemplateHandlerSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [OPTIONAL]
	// Patterns is path patterns that this handler
	// is registered to a server.
	// Default is not set.
	Patterns []string `protobuf:"bytes,1,rep,name=Patterns,json=patterns,proto3" json:"Patterns,omitempty"`
	// [OPTIONA]
	// Methods is the list of HTTP method this handler can handle.
	// Note that it depends on the multiplexer, or HTTP router
	// if this field can be used.
	// If not set, all methods are accepted.
	// Default is not set.
	Methods []HTTPMethod `protobuf:"varint,2,rep,packed,name=Methods,json=methods,proto3,enum=core.v1.HTTPMethod" json:"Methods,omitempty"`
	// [REQUIRED]
	// MIMEContents is the list of content that will be returned by this handler.
	// When no appropriate content were found,
	// not acceptable error will be returned to clients.
	// Default is not set.
	MIMEContents  []*MIMEContentSpec `protobuf:"bytes,3,rep,name=MIMEContents,json=mimeContents,proto3" json:"MIMEContents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateHandlerSpec) Reset() {
	*x = TemplateHandlerSpec{}
	mi := &file_core_v1_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateHandlerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateHandlerSpec) ProtoMessage() {}

func (x *TemplateHandlerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateHandlerSpec.ProtoReflect.Descriptor instead.
func (*TemplateHandlerSpec) Descriptor() ([]byte, []int) {
	return file_core_v1_template_proto_rawDescGZIP(), []int{1}
}

func (x *TemplateHandlerSpec) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *TemplateHandlerSpec) GetMethods() []HTTPMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *TemplateHandlerSpec) GetMIMEContents() []*MIMEContentSpec {
	if x != nil {
		return x.MIMEContents
	}
	return nil
}

// + MIMEContentSpec
// MIMEContentSpec is the specification for the MIMEContent.
type MIMEContentSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [REQUIRED]
	// MIMEType is the mediatype of this content.
	// See the following documents for available type.
	// https://www.iana.org/assignments/media-types/media-types.xhtml
	// Default is not set.
	MIMEType string `protobuf:"bytes,1,opt,name=MIMEType,json=mimeType,proto3" json:"MIMEType,omitempty"`
	// [OPTIONAL]
	// StatusCode is the http status code used to respond this content.
	// Default is [200].
	StatusCode int32 `protobuf:"varint,2,opt,name=StatusCode,json=statusCode,proto3" json:"StatusCode,omitempty"`
	// [OPTIONAL]
	// Header is the key-value pairs of HTTP headers
	// to add to the response.
	// Keys must be a valid http header name.
	// Default is not set.
	Header map[string]string `protobuf:"bytes,3,rep,name=Header,json=header,proto3" json:"Header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// [OPTIONAL]
	// TemplateType is the template engine type of this content.
	// Default is [Text].
	TemplateType TemplateType `protobuf:"varint,4,opt,name=TemplateType,json=templateType,proto3,enum=core.v1.TemplateType" json:"TemplateType,omitempty"`
	// [OPTIONAL]
	// Template is the template text to generate response body.
	// TemplateFile is prior to Template if both parameters are set.
	// Default is not set.
	Template string `protobuf:"bytes,5,opt,name=Template,json=template,proto3" json:"Template,omitempty"`
	// [OPTIONAL]
	// TemplateFile is the fail path to read template from.
	// TemplateFile is prior to Template if both parameters are set.
	// It does not matter wheather the path is relative or absolute.
	// Default is not set.
	TemplateFile  string `protobuf:"bytes,6,opt,name=TemplateFile,json=templateFile,proto3" json:"TemplateFile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MIMEContentSpec) Reset() {
	*x = MIMEContentSpec{}
	mi := &file_core_v1_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MIMEContentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MIMEContentSpec) ProtoMessage() {}

func (x *MIMEContentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MIMEContentSpec.ProtoReflect.Descriptor instead.
func (*MIMEContentSpec) Descriptor() ([]byte, []int) {
	return file_core_v1_template_proto_rawDescGZIP(), []int{2}
}

func (x *MIMEContentSpec) GetMIMEType() string {
	if x != nil {
		return x.MIMEType
	}
	return ""
}

func (x *MIMEContentSpec) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *MIMEContentSpec) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MIMEContentSpec) GetTemplateType() TemplateType {
	if x != nil {
		return x.TemplateType
	}
	return TemplateType_Text
}

func (x *MIMEContentSpec) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *MIMEContentSpec) GetTemplateFile() string {
	if x != nil {
		return x.TemplateFile
	}
	return ""
}

var File_core_v1_template_proto protoreflect.FileDescriptor

const file_core_v1_template_proto_rawDesc = "" +
	"\n" +
	"\x16core/v1/template.proto\x12\acore.v1\x1a\x1bbuf/validate/validate.proto\x1a\x12core/v1/http.proto\x1a\x15kernel/resource.proto\"\xa5\x01\n" +
	"\x0fTemplateHandler\x12\x1e\n" +
	"\n" +
	"APIVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04Kind\x18\x02 \x01(\tR\x04kind\x12,\n" +
	"\bMetadata\x18\x03 \x01(\v2\x10.kernel.MetadataR\bmetadata\x120\n" +
	"\x04Spec\x18\x04 \x01(\v2\x1c.core.v1.TemplateHandlerSpecR\x04spec\"\xb2\x01\n" +
	"\x13TemplateHandlerSpec\x12$\n" +
	"\bPatterns\x18\x01 \x03(\tB\b\xbaH\x05\x92\x01\x02\x18\x01R\bpatterns\x127\n" +
	"\aMethods\x18\x02 \x03(\x0e2\x13.core.v1.HTTPMethodB\b\xbaH\x05\x92\x01\x02\x18\x01R\amethods\x12<\n" +
	"\fMIMEContents\x18\x03 \x03(\v2\x18.core.v1.MIMEContentSpecR\fmimeContents\"\xee\x02\n" +
	"\x0fMIMEContentSpec\x12;\n" +
	"\bMIMEType\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z]+/[0-9a-zA-Z.+-]+$R\bmimeType\x12*\n" +
	"\n" +
	"StatusCode\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe7\a(\x00R\n" +
	"statusCode\x12<\n" +
	"\x06Header\x18\x03 \x03(\v2$.core.v1.MIMEContentSpec.HeaderEntryR\x06header\x129\n" +
	"\fTemplateType\x18\x04 \x01(\x0e2\x15.core.v1.TemplateTypeR\ftemplateType\x12\x1a\n" +
	"\bTemplate\x18\x05 \x01(\tR\btemplate\x12\"\n" +
	"\fTemplateFile\x18\x06 \x01(\tR\ftemplateFile\x1a9\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*0\n" +
	"\fTemplateType\x12\b\n" +
	"\x04Text\x10\x00\x12\n" +
	"\n" +
	"\x06GoText\x10\x01\x12\n" +
	"\n" +
	"\x06GoHTML\x10\x02B9Z7github.com/aileron-gateway/aileron-gateway/apis/core/v1b\x06proto3"

var (
	file_core_v1_template_proto_rawDescOnce sync.Once
	file_core_v1_template_proto_rawDescData []byte
)

func file_core_v1_template_proto_rawDescGZIP() []byte {
	file_core_v1_template_proto_rawDescOnce.Do(func() {
		file_core_v1_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_template_proto_rawDesc), len(file_core_v1_template_proto_rawDesc)))
	})
	return file_core_v1_template_proto_rawDescData
}

var file_core_v1_template_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_v1_template_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_v1_template_proto_goTypes = []any{
	(TemplateType)(0),           // 0: core.v1.TemplateType
	(*TemplateHandler)(nil),     // 1: core.v1.TemplateHandler
	(*TemplateHandlerSpec)(nil), // 2: core.v1.TemplateHandlerSpec
	(*MIMEContentSpec)(nil),     // 3: core.v1.MIMEContentSpec
	nil,                         // 4: core.v1.MIMEContentSpec.HeaderEntry
	(*kernel.Metadata)(nil),     // 5: kernel.Metadata
	(HTTPMethod)(0),             // 6: core.v1.HTTPMethod
}
var file_core_v1_template_proto_depIdxs = []int32{
	5, // 0: core.v1.TemplateHandler.Metadata:type_name -> kernel.Metadata
	2, // 1: core.v1.TemplateHandler.Spec:type_name -> core.v1.TemplateHandlerSpec
	6, // 2: core.v1.TemplateHandlerSpec.Methods:type_name -> core.v1.HTTPMethod
	3, // 3: core.v1.TemplateHandlerSpec.MIMEContents:type_name -> core.v1.MIMEContentSpec
	4, // 4: core.v1.MIMEContentSpec.Header:type_name -> core.v1.MIMEContentSpec.HeaderEntry
	0, // 5: core.v1.MIMEContentSpec.TemplateType:type_name -> core.v1.TemplateType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_core_v1_template_proto_init() }
func file_core_v1_template_proto_init() {
	if File_core_v1_template_proto != nil {
		return
	}
	file_core_v1_http_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_template_proto_rawDesc), len(file_core_v1_template_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_v1_template_proto_goTypes,
		DependencyIndexes: file_core_v1_template_proto_depIdxs,
		EnumInfos:         file_core_v1_template_proto_enumTypes,
		MessageInfos:      file_core_v1_template_proto_msgTypes,
	}.Build()
	File_core_v1_template_proto = out.File
	file_core_v1_template_proto_goTypes = nil
	file_core_v1_template_proto_depIdxs = nil
}
