version: '3'
env:
  AILERON_CMD: "./aileron"
tasks:
  default:
    deps: ["http1"]

  http1:
    deps: ["server-http1", "config-http1"]
  config-http1:
    cmd: "{{.AILERON_CMD}} -f ./config-http1.yaml"
  server-http1:
    cmd: "go run ./server-http1.go"

  http2:
    deps: ["server-http2", "config-http2"]
  config-http2:
    cmd: "{{.AILERON_CMD}} -f ./config-http2.yaml"
  server-http2:
    cmd: "go run ./server-http2.go"

  http3:
    deps: ["server-http3", "config-http3"]
  config-http3:
    cmd: "{{.AILERON_CMD}} -f ./config-http3.yaml"
  server-http3:
    cmd: "go run ./server-http3.go"
