// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.0
// source: kernel/commonkey.proto

package kernel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommonKeyCryptType is the algorithms of common key encryption.
type CommonKeyCryptType int32

const (
	CommonKeyCryptType_CommonKeyCryptTypeUnknown CommonKeyCryptType = 0 // Unknown crypt type.
	CommonKeyCryptType_AESGCM                    CommonKeyCryptType = 1 // AES-GCM cipher. Key length must be 16, 24, 32 bytes for AES-128, AES-192, AES-256.
	CommonKeyCryptType_AESCBC                    CommonKeyCryptType = 2 // AES-CBC cipher. Key length must be 16, 24, 32 bytes for AES-128, AES-192, AES-256.
	CommonKeyCryptType_AESCFB                    CommonKeyCryptType = 3 // AES-CFB cipher. Key length must be 16, 24, 32 bytes for AES-128, AES-192, AES-256.
	CommonKeyCryptType_AESCTR                    CommonKeyCryptType = 4 // AES-CTR cipher. Key length must be 16, 24, 32 bytes for AES-128, AES-192, AES-256.
	CommonKeyCryptType_AESOFB                    CommonKeyCryptType = 5 // AES-OFB cipher. Key length must be 16, 24, 32 bytes for AES-128, AES-192, AES-256.
)

// Enum value maps for CommonKeyCryptType.
var (
	CommonKeyCryptType_name = map[int32]string{
		0: "CommonKeyCryptTypeUnknown",
		1: "AESGCM",
		2: "AESCBC",
		3: "AESCFB",
		4: "AESCTR",
		5: "AESOFB",
	}
	CommonKeyCryptType_value = map[string]int32{
		"CommonKeyCryptTypeUnknown": 0,
		"AESGCM":                    1,
		"AESCBC":                    2,
		"AESCFB":                    3,
		"AESCTR":                    4,
		"AESOFB":                    5,
	}
)

func (x CommonKeyCryptType) Enum() *CommonKeyCryptType {
	p := new(CommonKeyCryptType)
	*p = x
	return p
}

func (x CommonKeyCryptType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommonKeyCryptType) Descriptor() protoreflect.EnumDescriptor {
	return file_kernel_commonkey_proto_enumTypes[0].Descriptor()
}

func (CommonKeyCryptType) Type() protoreflect.EnumType {
	return &file_kernel_commonkey_proto_enumTypes[0]
}

func (x CommonKeyCryptType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommonKeyCryptType.Descriptor instead.
func (CommonKeyCryptType) EnumDescriptor() ([]byte, []int) {
	return file_kernel_commonkey_proto_rawDescGZIP(), []int{0}
}

var File_kernel_commonkey_proto protoreflect.FileDescriptor

var file_kernel_commonkey_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x6b,
	0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c,
	0x2a, 0x6f, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x43, 0x72, 0x79,
	0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x4b, 0x65, 0x79, 0x43, 0x72, 0x79, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x45, 0x53, 0x47, 0x43, 0x4d, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x45, 0x53, 0x43, 0x42, 0x43, 0x10, 0x02, 0x12, 0x0a, 0x0a,
	0x06, 0x41, 0x45, 0x53, 0x43, 0x46, 0x42, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x45, 0x53,
	0x43, 0x54, 0x52, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x45, 0x53, 0x4f, 0x46, 0x42, 0x10,
	0x05, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x69, 0x6c, 0x65, 0x72, 0x6f, 0x6e, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f,
	0x61, 0x69, 0x6c, 0x65, 0x72, 0x6f, 0x6e, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f,
	0x61, 0x70, 0x69, 0x73, 0x2f, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_kernel_commonkey_proto_rawDescOnce sync.Once
	file_kernel_commonkey_proto_rawDescData []byte
)

func file_kernel_commonkey_proto_rawDescGZIP() []byte {
	file_kernel_commonkey_proto_rawDescOnce.Do(func() {
		file_kernel_commonkey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kernel_commonkey_proto_rawDesc), len(file_kernel_commonkey_proto_rawDesc)))
	})
	return file_kernel_commonkey_proto_rawDescData
}

var file_kernel_commonkey_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kernel_commonkey_proto_goTypes = []any{
	(CommonKeyCryptType)(0), // 0: kernel.CommonKeyCryptType
}
var file_kernel_commonkey_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kernel_commonkey_proto_init() }
func file_kernel_commonkey_proto_init() {
	if File_kernel_commonkey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kernel_commonkey_proto_rawDesc), len(file_kernel_commonkey_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kernel_commonkey_proto_goTypes,
		DependencyIndexes: file_kernel_commonkey_proto_depIdxs,
		EnumInfos:         file_kernel_commonkey_proto_enumTypes,
	}.Build()
	File_kernel_commonkey_proto = out.File
	file_kernel_commonkey_proto_goTypes = nil
	file_kernel_commonkey_proto_depIdxs = nil
}
