#!/bin/sh

set -e

#----------------------------------------------------

echo "Running postrm script:" $@

if [ "$1" -eq 0 ] ; then
    if [ -z "$(ls -A /var/lib/aileron/)" ]; then
        rm -rf /var/lib/aileron/
    fi
fi

#----------------------------------------------------
exit 0
