version: '3'
env:
  AILERON_CMD: "./aileron"
tasks:
  default:
    deps: ["single"]
  single:
    cmd: "{{.AILERON_CMD}} -f ./config-single.yaml"
  multiple:
    cmd: "{{.AILERON_CMD}} -f ./config-multiple.yaml"
