version: '3'
env:
  AILERON_CMD: "./aileron"
tasks:
  default:
    deps: ["server"]
  server:
    cmd: "{{.AILERON_CMD}} -f ./config.yaml"
  withmock:
    deps: ["upstream", "server"]
  upstream:
    cmd: "go run ./server.go"
