#!/bin/sh

set -e

#----------------------------------------------------

echo "Running postrm script:" $@

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -z "$(ls -A /var/lib/aileron/)" ]; then
        rm -rf /var/lib/aileron/
    fi
fi

#----------------------------------------------------
exit 0
