version: "3"

services:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    hostname: cadvisor
    restart: always
    ports:
      - "18080:18080"
    command:
      # Check other options from the link below.
      # https://github.com/google/cadvisor/blob/master/docs/runtime_options.md
      # https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md
      - "--port=18080"
      - "--docker_only=false"
      - "--enable_load_reader=true"
      - "--application_metrics_count_limit=1000"
      - "--prometheus_endpoint=/metrics"
      - "--disable_metrics="
      - "--enable_metrics=advtcp,app,cpu,cpuLoad,cpu_topology,cpuset,disk,diskIO,hugetlb,memory,memory_numa,network,oom_event,percpu,perf_event,process,referenced_memory,resctrl,sched,tcp,udp"
      - "--disable_root_cgroup_stats=false"
      - "--profiling=true"
    privileged: true
    pid: "host"
    userns_mode: "host"
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    deploy:
      mode: global
    volumes:
      - /:/rootfs:ro
      - /cgroup:/cgroup:ro
      - /dev:/dev:ro
      - /dev/disk/:/dev/disk:ro
      - /etc:/etc:ro
      - /proc:/proc:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:ro
    devices:
      - "/dev/kmsg:/dev/kmsg"
