apiVersion: core/v1
kind: Entrypoint
spec:
  defaultLogger:
    apiVersion: core/v1
    kind: SLogger
    namespace: sampleNamespace
    name: default
  runners:
    - apiVersion: core/v1
      kind: HTTPServer
      namespace: sampleNamespace
      name: EchoServer
    - apiVersion: core/v1
      kind: HTTPServer
      namespace: sampleNamespace
      name: ReverseProxyServer

---
apiVersion: core/v1
kind: SLogger
metadata:
  name: default
  namespace: sampleNamespace
spec:
  level: "Debug"
  logOutput:
    logFileName: slogger

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  name: EchoServer
  namespace: sampleNamespace
spec:
  addr: ":8000"
  virtualHosts:
    - hosts:
        - localhost:8000
      handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler
            namespace: sampleNamespace
            name: default
        - handler:
            apiVersion: app/v1
            kind: HealthCheckHandler
            namespace: sampleNamespace
            name: default

---
apiVersion: core/v1
kind: HTTPServer
metadata:
  name: ReverseProxyServer
  namespace: sampleNamespace
spec:
  addr: ":8080"
  # listener:
  #   allowedNetworks:
  #     - "::1/64"
  #     - "127.0.0.1/24"
  virtualHosts:
    - middleware:
        # - apiVersion: app/v1
        #   kind: CSRFMiddleware
        #   namespace: sampleNamespace
        #   name: default
        - apiVersion: app/v1
          kind: TrackingMiddleware
          namespace: sampleNamespace
          name: default
        - apiVersion: core/v1
          kind: HTTPLogger
          namespace: sampleNamespace
          name: default
        - apiVersion: app/v1
          kind: CompressionMiddleware
          namespace: example
          name: default
      handlers:
        - handler:
            apiVersion: core/v1
            kind: ReverseProxyHandler
            namespace: sampleNamespace
            name: default

---
apiVersion: core/v1
kind: ErrorHandler
metadata:
  name: default
  namespace: sampleNamespace
spec:

---
apiVersion: app/v1
kind: EchoHandler
metadata:
  name: default
  namespace: sampleNamespace
spec: {}

---
apiVersion: app/v1
kind: HealthCheckHandler
metadata:
  name: default
  namespace: sampleNamespace
spec:

---
apiVersion: core/v1
kind: ReverseProxyHandler
metadata:
  namespace: sampleNamespace
  name: default
spec:
  patterns:
    - "/"
  # methods:
  loadBalancers:
    # - pathMatcher:
    #     match: "/(?P<key>\\w+)/(?P<value>\\w+)"
    #     matchType: Regex
    #     rewrite: "/$value/$key"
    #   upstreams:
    #     # - url: http://worldtimeapi.org
    #     # - url: http://localhost:8000/
    # - pathMatcher:
    #     match: "^/foo/.*"
    #     matchType: Regex
    #   upstreams:
    #     # - url: http://worldtimeapi.org
    #     # - url: http://localhost:8000/
    - pathMatcher:
        match: "^/bar/.*"
        matchType: Regex
      upstreams:
        # - url: http://worldtimeapi.org
        # - url: http://localhost:8000/
    - pathMatcher:
        # trimPrefix: "/api"
        match: ".*"
        matchType: Regex
      upstreams:
        # - url: http://postman-echo.com
        # - url: http://worldtimeapi.org
        - url: http://httpbin.org
        # - url: http://localhost:8000/

---
apiVersion: core/v1
kind: MessageLogCreator
metadata:
  name: default
  namespace: sampleNamespace
spec:
  location: "Asia/Tokyo"
  noLocation: true

---
apiVersion: core/v1
kind: HTTPLogger
metadata:
  name: default
  namespace: sampleNamespace
spec:
  logCreator:
    apiVersion: core/v1
    kind: MessageLogCreator
    name: default
    namespace: sampleNamespace

---
apiVersion: app/v1
kind: TrackingMiddleware
metadata:
  name: default
  namespace: sampleNamespace
spec:
  requestID:
    fromHeaderName: "X-Request-ID"
    # proxyHeaderName: "X-Internal-Request-ID"
  traceID:
    proxyHeaderName: "X-Internal-Trace-ID"

---
apiVersion: app/v1
kind: CORSMiddleware
metadata:
  name: default
  namespace: sampleNamespace
spec:
  # targetMIMEs:

---
apiVersion: app/v1
kind: CSRFMiddleware
metadata:
  name: default
  namespace: sampleNamespace
spec:

---
apiVersion: app/v1
kind: CompressionMiddleware
metadata:
  namespace: example
  name: default
spec:
  minimumSize: 100
