version: 1

goos: darwin
goarch: amd64

main: ./cmd/aileron/
binary: aileron-{{ .Os }}-{{ .Arch }}
dir: _output/

env:
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo,osusergo

ldflags:
  - "-w"
  - "-s"
  - '-extldflags "-static"'
  - "-X main.version={{ .Env.VERSION }}"
