version: 1

goos: linux
goarch: s390x

main: cmd/aileron/
# dir: _output/bin/
binary: _output/aileron-{{ .Os }}-{{ .Arch }}

env:
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo,osusergo

ldflags:
  - "-w"
  - "-s"
  - '-extldflags "-static"'
  - "-X main.version={{ .Env.VERSION }}"
