version: 1

goos: linux
goarch: 386

main: ./cmd/aileron/
dir: _output/bin/
binary: aileron-{{ .Os }}-{{ .Arch }}

env:
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo,osusergo

ldflags:
  - "-w"
  - "-s"
  - '-extldflags "-static"'
  - "-X main.version={{ .Env.VERSION }}"
