version: 1

goos: netbsd
goarch: arm

main: ./cmd/aileron/
dir: _output/bin/{{ .Os }}-{{ .Arch }}7/
binary: aileron

env:
  - CGO_ENABLED=0
  - GOARM=7

flags:
  - -trimpath
  - -tags=netgo,osusergo

ldflags:
  - "-w"
  - "-s"
  - '-extldflags "-static"'
  - "-X main.version={{ .Env.VERSION }}"
