version: 1

goos: openbsd
goarch: 386

main: ./cmd/aileron/
binary: _output/bin/{{ .Os }}-{{ .Arch }}/aileron

env:
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo,osusergo

ldflags:
  - "-w"
  - "-s"
  - '-extldflags "-static"'
  - "-X main.version={{ .Env.VERSION }}"
