version: 1

goos: windows
goarch: 386

main: ./cmd/aileron/
binary: aileron-{{ .Os }}-{{ .Arch }}.exe

env:
  - CGO_ENABLED=0

flags:
  - -trimpath

ldflags:
  - "-w"
  - "-s"
  - '-extldflags "-static"'
  - "-X main.version={{ .Env.VERSION }}"
