version: 1

goos: windows
goarch: arm64

main: ../../cmd/aileron/
dir: _output/bin/
binary: aileron-{{ .Os }}-{{ .Arch }}.exe

env:
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo,osusergo

ldflags:
  - "-w"
  - "-s"
  - '-extldflags "-static"'
  - "-X main.version={{ .Env.VERSION }}"
