version: 1

goos: windows
goarch: amd64

main: ./cmd/aileron/
binary: _output/bin/{{ .Os }}-{{ .Arch }}/aileron.exe

env:
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo,osusergo

ldflags:
  - "-w"
  - "-s"
  - '-extldflags "-static"'
  - "-X main.version={{ .Env.VERSION }}"
