apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - handlers:
        - handler:
            apiVersion: core/v1
            kind: ReverseProxyHandler

---
apiVersion: core/v1
kind: ReverseProxyHandler
spec:
  loadBalancers:
    - pathMatcher:
        match: "/"
        matchType: Prefix
      lbAlgorithm: DirectHash # Use DirectHash load balancer.
      hashers: # DirectHasher requires at least 1 hasher.
        - hasherType: Header
          hashAlg: FNV1_32
          key: Hash-Key
        - hasherType: ClientAddr
          hashAlg: FNV1_64
      upstreams:
        - url: http://localhost:8001
        - url: http://localhost:8002
        - url: http://localhost:8003
        - url: http://localhost:8004
        - url: http://localhost:8005
