apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - handlers:
        - handler:
            apiVersion: core/v1
            kind: ReverseProxyHandler

---
apiVersion: core/v1
kind: ReverseProxyHandler
spec:
  loadBalancers:
    - pathMatcher:
        match: "/"
        matchType: Prefix
      lbAlgorithm: RingHash # Use RingHash load balancer.
      hashTableSize: 1009 # Optional. At least 100*upstreams.
      hashers: # RingHash requires at least 1 hasher.
        - hasherType: Header
          key: Hash-Key
        - hasherType: ClientAddr
      upstreams:
        - url: http://localhost:8001
        - url: http://localhost:8002
        - url: http://localhost:8003
        - url: http://localhost:8004
        - url: http://localhost:8005
