apiVersion: core/v1
kind: Entrypoint
spec:
  runners:
    - apiVersion: core/v1
      kind: HTTPServer

---
apiVersion: core/v1
kind: HTTPServer
spec:
  addr: ":8080"
  virtualHosts:
    - hosts: []
      middleware:
        - apiVersion: app/v1
          kind: KeyAuthnMiddleware
      handlers:
        - handler:
            apiVersion: app/v1
            kind: EchoHandler

---
apiVersion: app/v1
kind: EchoHandler
spec: {}

---
apiVersion: app/v1
kind: KeyAuthnMiddleware
spec:
  # hashAlg: SHA256
  # hmacSecret: ZXhhbXBsZV9wYXNzd29yZA== # Base64("example_password")
  # envProvider:
  #   encoding: Base16
  # fileProvider:
  #   # encoding: Base16
  #   paths:
  #     - ./_example/authn-key/keys.list
