name: Static Analysis

on:
  workflow_dispatch: {}
  push:
    branches: ["**"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: make spell
      - run: make vuln
      - run: make lint
