name: Release Container

on:
  workflow_call: {}

permissions:
  contents: read
  packages: write

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: aileron

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: ko-build/setup-ko@v0.8
      - run: |
          export VERSION=$(git describe --tags --always --dirty | sed 's/-dirty//')
          ko build -v -B --sbom=none --tags=latest --tags=${VERSION} ./cmd/aileron/
      - name: Build on nonroot
        run: |
          export VERSION=$(git describe --tags --always --dirty | sed 's/-dirty//')
          export KO_DEFAULTBASEIMAGE=gcr.io/distroless/static:nonroot
          ko build -v -B --sbom=none --tags=latest --tags=${VERSION} ./cmd/aileron/
      - name: Build on debug
        run: |
          export VERSION=$(git describe --tags --always --dirty | sed 's/-dirty//')
          export KO_DEFAULTBASEIMAGE=gcr.io/distroless/static:debug
          ko build -v -B --sbom=none --tags=${VERSION}-debug ./cmd/aileron/
      - name: Build on debug-nonroot
        run: |
          export VERSION=$(git describe --tags --always --dirty | sed 's/-dirty//')
          export KO_DEFAULTBASEIMAGE=gcr.io/distroless/static:debug-nonroot
          ko build -v -B --sbom=none --tags=${VERSION}-debug-nonroot ./cmd/aileron/
