name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-test.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

permissions:
  actions: read
  contents: write
  id-token: write
  packages: write

jobs:
  proto:
    uses: ./.github/workflows/proto.yaml
    secrets: inherit

  tidy:
    needs: proto
    uses: ./.github/workflows/tidy.yaml
    secrets: inherit

  checks:
    needs: tidy
    uses: ./.github/workflows/checks.yaml
    secrets: inherit

  unit-test:
    needs: checks
    uses: ./.github/workflows/test-unit.yaml
    secrets: inherit

  integration-test:
    needs: unit-test
    uses: ./.github/workflows/test-integration.yaml
    secrets: inherit

  example-test:
    needs: integration-test
    uses: ./.github/workflows/test-example.yaml
    secrets: inherit

  release-binary:
    needs: example-test
    uses: ./.github/workflows/release-binary.yaml
    secrets: inherit

  release-container:
    needs: example-test
    uses: ./.github/workflows/release-container.yaml
    secrets: inherit
