name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-test.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  actions: read
  contents: write
  id-token: write
  packages: write

jobs:
  test-suite:
    uses: ./.github/workflows/test-suite.yaml
    secrets: inherit

  release-binary:
    needs: test-suite
    uses: ./.github/workflows/release-binary.yaml
    secrets: inherit

  release-container:
    needs: test-suite
    uses: ./.github/workflows/release-container.yaml
    secrets: inherit
