name: Integration Test

on:
  push:
    branches: ["**"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  proto:
    uses: ./.github/workflows/proto.yaml
    permissions:
      contents: write

  test:
    needs: proto
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: make integration
        run: |
          set +o pipefail
          make integration 2>&1 | tee _output/integration-test.log
      - uses: actions/upload-artifact@v4
        with:
          name: integration-test-${{ matrix.os }}
          path: _output/**
          retention-days: 1

  qemu:
    needs: proto
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        arch:
          - "amd64"
          - "arm"
          - "arm64"
          - "ppc64"
          - "ppc64le"
          - "riscv64"
          - "s390x"
          - "loong64" # Can be removed.
          - "386" # Can be removed.
          - "mips" # Can be removed.
          - "mips64" # Can be removed.
          - "mips64le" # Can be removed.
          - "mipsle" # Can be removed.
          - "sparc64" # Can be removed.
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: |
          sudo add-apt-repository -y ppa:canonical-server/server-backports
          sudo apt -y update
          sudo apt -y install qemu-user
      - name: make test
        run: |
          make go-test-qemu GOARCH=${{ matrix.arch }} GO_TEST_TARGET=./test/integration/... EXTRA_ARGS="-tags=integration"
