name: Integration Test

on:
  push:
    branches: ["**"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  proto:
    uses: ./.github/workflows/proto.yaml
    permissions:
      contents: write

  test:
    needs: proto
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: make integration
        run: |
          set +o pipefail
          make integration 2>&1 | tee _output/integration-test.log
      - uses: actions/upload-artifact@v4
        with:
          name: integration-test-${{ matrix.os }}
          path: _output/**
          retention-days: 1

  # qemu:
  #   needs: proto
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   strategy:
  #     matrix:
  #       arch:
  #         - { go: "amd64", qemu: "x86_64" }
  #         - { go: "arm", qemu: "arm" }
  #         - { go: "arm64", qemu: "aarch64" }
  #         - { go: "ppc64", qemu: "ppc64" }
  #         - { go: "ppc64le", qemu: "ppc64le" }
  #         - { go: "riscv64", qemu: "riscv64" }
  #         - { go: "s390x", qemu: "s390x" }
  #   steps:
  #     - run: git config --global core.autocrlf false
  #     - uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #     - uses: actions/setup-go@v5
  #       with:
  #         go-version: stable
  #     - run: |
  #         sudo add-apt-repository -y ppa:canonical-server/server-backports
  #         sudo apt -y update
  #         sudo apt -y install qemu-user
  #     - name: make test
  #       run: |
  #         mkdir -p test-bin/
  #         GOARCH=${{ matrix.arch.go }} go test -v -cover -c -o test-bin/ -tags=integration ./test/integration/...
  #         for target in ./test-bin/*; do
  #           echo "RUNNING TEST: ${target}"
  #           TEST_DIR=./test/ qemu-${{ matrix.arch.qemu }} ${target}
  #         done
