name: Test Suite

on:
  workflow_dispatch: {}
  workflow_call: {}
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  proto:
    uses: ./.github/workflows/proto.yaml
    secrets: inherit

  checks:
    needs: proto
    uses: ./.github/workflows/checks.yaml
    secrets: inherit

  unit-test:
    needs: checks
    uses: ./.github/workflows/test-unit.yaml
    secrets: inherit

  integration-test:
    needs: unit-test
    uses: ./.github/workflows/test-integration.yaml
    secrets: inherit

  e2e-test:
    needs: integration-test
    uses: ./.github/workflows/test-e2e.yaml
    secrets: inherit
