name: E2E Test

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      matrix:
        os:
          - ubuntu
          # - windows
          # - macos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: make e2e
        run: |
          set +o pipefail
          mkdir -p _output/
          make e2e 2>&1 | tee _output/e2e-test.log
      - uses: actions/upload-artifact@v4
        with:
          name: e2e-test-${{ matrix.os }}
          path: _output/**
          retention-days: 7
