name: Proto

on:
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  contents: write

jobs:
  proto:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go mod tidy
      - name: git commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -s -m "go mod tidy" || true
          git push || true
